// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: attributes.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextMediaAttribute_TextMediaAttributeType int32

const (
	// * ADDRESS - P. Sherman, 42 Wallaby Way, Sydney
	TextMediaAttribute_TextMediaAttributeType_ADDRESS TextMediaAttribute_TextMediaAttributeType = 0
	// * PHONE - 867-5309
	TextMediaAttribute_TextMediaAttributeType_PHONE TextMediaAttribute_TextMediaAttributeType = 1
	// * EMAIL - steve@apple.com
	TextMediaAttribute_TextMediaAttributeType_EMAIL TextMediaAttribute_TextMediaAttributeType = 2
	// * MENTION - @evan
	TextMediaAttribute_TextMediaAttributeType_MENTION TextMediaAttribute_TextMediaAttributeType = 3
)

// Enum value maps for TextMediaAttribute_TextMediaAttributeType.
var (
	TextMediaAttribute_TextMediaAttributeType_name = map[int32]string{
		0: "ADDRESS",
		1: "PHONE",
		2: "EMAIL",
		3: "MENTION",
	}
	TextMediaAttribute_TextMediaAttributeType_value = map[string]int32{
		"ADDRESS": 0,
		"PHONE":   1,
		"EMAIL":   2,
		"MENTION": 3,
	}
)

func (x TextMediaAttribute_TextMediaAttributeType) Enum() *TextMediaAttribute_TextMediaAttributeType {
	p := new(TextMediaAttribute_TextMediaAttributeType)
	*p = x
	return p
}

func (x TextMediaAttribute_TextMediaAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextMediaAttribute_TextMediaAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_attributes_proto_enumTypes[0].Descriptor()
}

func (TextMediaAttribute_TextMediaAttributeType) Type() protoreflect.EnumType {
	return &file_attributes_proto_enumTypes[0]
}

func (x TextMediaAttribute_TextMediaAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextMediaAttribute_TextMediaAttributeType.Descriptor instead.
func (TextMediaAttribute_TextMediaAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{0}
}

type TextFormatAttribute_TextFormatAttributeType int32

const (
	TextFormatAttribute_TextFormatAttributeType_BOLD      TextFormatAttribute_TextFormatAttributeType = 0
	TextFormatAttribute_TextFormatAttributeType_ITALICS   TextFormatAttribute_TextFormatAttributeType = 1
	TextFormatAttribute_TextFormatAttributeType_UNDERLINE TextFormatAttribute_TextFormatAttributeType = 2
)

// Enum value maps for TextFormatAttribute_TextFormatAttributeType.
var (
	TextFormatAttribute_TextFormatAttributeType_name = map[int32]string{
		0: "BOLD",
		1: "ITALICS",
		2: "UNDERLINE",
	}
	TextFormatAttribute_TextFormatAttributeType_value = map[string]int32{
		"BOLD":      0,
		"ITALICS":   1,
		"UNDERLINE": 2,
	}
)

func (x TextFormatAttribute_TextFormatAttributeType) Enum() *TextFormatAttribute_TextFormatAttributeType {
	p := new(TextFormatAttribute_TextFormatAttributeType)
	*p = x
	return p
}

func (x TextFormatAttribute_TextFormatAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextFormatAttribute_TextFormatAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_attributes_proto_enumTypes[1].Descriptor()
}

func (TextFormatAttribute_TextFormatAttributeType) Type() protoreflect.EnumType {
	return &file_attributes_proto_enumTypes[1]
}

func (x TextFormatAttribute_TextFormatAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextFormatAttribute_TextFormatAttributeType.Descriptor instead.
func (TextFormatAttribute_TextFormatAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{1}
}

type TextAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range *Range `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// Types that are assignable to Attribute:
	//
	//	*TextAttribute_FormatAttribute
	//	*TextAttribute_MediaAttribute
	//	*TextAttribute_UrlAttribute
	//	*TextAttribute_Mention
	//	*TextAttribute_ScaleAttribute
	Attribute isTextAttribute_Attribute `protobuf_oneof:"attribute"`
}

func (x *TextAttribute) Reset() {
	*x = TextAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAttribute) ProtoMessage() {}

func (x *TextAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAttribute.ProtoReflect.Descriptor instead.
func (*TextAttribute) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *TextAttribute) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (m *TextAttribute) GetAttribute() isTextAttribute_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (x *TextAttribute) GetFormatAttribute() *TextFormatAttribute {
	if x, ok := x.GetAttribute().(*TextAttribute_FormatAttribute); ok {
		return x.FormatAttribute
	}
	return nil
}

func (x *TextAttribute) GetMediaAttribute() *TextMediaAttribute {
	if x, ok := x.GetAttribute().(*TextAttribute_MediaAttribute); ok {
		return x.MediaAttribute
	}
	return nil
}

func (x *TextAttribute) GetUrlAttribute() *TextUrlAttribute {
	if x, ok := x.GetAttribute().(*TextAttribute_UrlAttribute); ok {
		return x.UrlAttribute
	}
	return nil
}

func (x *TextAttribute) GetMention() *MentionAttribute {
	if x, ok := x.GetAttribute().(*TextAttribute_Mention); ok {
		return x.Mention
	}
	return nil
}

func (x *TextAttribute) GetScaleAttribute() *TextScaleAttribute {
	if x, ok := x.GetAttribute().(*TextAttribute_ScaleAttribute); ok {
		return x.ScaleAttribute
	}
	return nil
}

type isTextAttribute_Attribute interface {
	isTextAttribute_Attribute()
}

type TextAttribute_FormatAttribute struct {
	FormatAttribute *TextFormatAttribute `protobuf:"bytes,2,opt,name=formatAttribute,proto3,oneof"`
}

type TextAttribute_MediaAttribute struct {
	MediaAttribute *TextMediaAttribute `protobuf:"bytes,3,opt,name=mediaAttribute,proto3,oneof"`
}

type TextAttribute_UrlAttribute struct {
	UrlAttribute *TextUrlAttribute `protobuf:"bytes,4,opt,name=urlAttribute,proto3,oneof"`
}

type TextAttribute_Mention struct {
	Mention *MentionAttribute `protobuf:"bytes,5,opt,name=mention,proto3,oneof"`
}

type TextAttribute_ScaleAttribute struct {
	ScaleAttribute *TextScaleAttribute `protobuf:"bytes,6,opt,name=scaleAttribute,proto3,oneof"`
}

func (*TextAttribute_FormatAttribute) isTextAttribute_Attribute() {}

func (*TextAttribute_MediaAttribute) isTextAttribute_Attribute() {}

func (*TextAttribute_UrlAttribute) isTextAttribute_Attribute() {}

func (*TextAttribute_Mention) isTextAttribute_Attribute() {}

func (*TextAttribute_ScaleAttribute) isTextAttribute_Attribute() {}

// *
// Holds information for scaling the text message font size up or down by the given double scale.
// This is used for the Expressive Text feature: https://snapchat.quip.com/EL7UAqDvJ2L0
type TextScaleAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scale float64 `protobuf:"fixed64,1,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *TextScaleAttribute) Reset() {
	*x = TextScaleAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextScaleAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextScaleAttribute) ProtoMessage() {}

func (x *TextScaleAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextScaleAttribute.ProtoReflect.Descriptor instead.
func (*TextScaleAttribute) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *TextScaleAttribute) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// *
// Holds any user id that is mentioned by sender (i.e @bobby).
// This should be used to identify the user mentioned, especially in the case of
// a user name change after the message has been sent, to handle actions
// performed on the message (e.g. clicking on mentioned user).
type MentionAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *UUID `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *MentionAttribute) Reset() {
	*x = MentionAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MentionAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionAttribute) ProtoMessage() {}

func (x *MentionAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionAttribute.ProtoReflect.Descriptor instead.
func (*MentionAttribute) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *MentionAttribute) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

// *
// Holds any url attributes we found through parsing the message. These are
// either deeplinks or regular URLs
type TextUrlAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// * https://www.apple.com, snapchat://maps/los_angeles
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *TextUrlAttribute) Reset() {
	*x = TextUrlAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextUrlAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextUrlAttribute) ProtoMessage() {}

func (x *TextUrlAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextUrlAttribute.ProtoReflect.Descriptor instead.
func (*TextUrlAttribute) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{3}
}

func (x *TextUrlAttribute) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// *
// Holds any "media" parsing attributes we found. Those could include phone
// numbers, emails, mentions. They are rendered as media cards within chat and
// require a range and type
type TextMediaAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextMediaAttributeType TextMediaAttribute_TextMediaAttributeType `protobuf:"varint,2,opt,name=textMediaAttributeType,proto3,enum=attributes.TextMediaAttribute_TextMediaAttributeType" json:"textMediaAttributeType,omitempty"`
}

func (x *TextMediaAttribute) Reset() {
	*x = TextMediaAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextMediaAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMediaAttribute) ProtoMessage() {}

func (x *TextMediaAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMediaAttribute.ProtoReflect.Descriptor instead.
func (*TextMediaAttribute) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{4}
}

func (x *TextMediaAttribute) GetTextMediaAttributeType() TextMediaAttribute_TextMediaAttributeType {
	if x != nil {
		return x.TextMediaAttributeType
	}
	return TextMediaAttribute_TextMediaAttributeType_ADDRESS
}

type TextFormatAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextFormatAttributeType TextFormatAttribute_TextFormatAttributeType `protobuf:"varint,2,opt,name=textFormatAttributeType,proto3,enum=attributes.TextFormatAttribute_TextFormatAttributeType" json:"textFormatAttributeType,omitempty"`
}

func (x *TextFormatAttribute) Reset() {
	*x = TextFormatAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextFormatAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextFormatAttribute) ProtoMessage() {}

func (x *TextFormatAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextFormatAttribute.ProtoReflect.Descriptor instead.
func (*TextFormatAttribute) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{5}
}

func (x *TextFormatAttribute) GetTextFormatAttributeType() TextFormatAttribute_TextFormatAttributeType {
	if x != nil {
		return x.TextFormatAttributeType
	}
	return TextFormatAttribute_TextFormatAttributeType_BOLD
}

var File_attributes_proto protoreflect.FileDescriptor

var file_attributes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x75,
	0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x03, 0x0a, 0x0d, 0x54, 0x65, 0x78,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x4b, 0x0a, 0x0f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x48, 0x0a, 0x0e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x75, 0x72, 0x6c, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x55, 0x72,
	0x6c, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x72,
	0x6c, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x6d, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x6e,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x53, 0x63,
	0x61, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x42, 0x0b,
	0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x54,
	0x65, 0x78, 0x74, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x4d, 0x65, 0x6e, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x75,
	0x69, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x24, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x55, 0x72, 0x6c, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x6d, 0x0a, 0x16,
	0x74, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x54, 0x65, 0x78,
	0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x16, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x13,
	0x54, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x12, 0x71, 0x0a, 0x17, 0x74, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x54, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x17, 0x74,
	0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x5b, 0x0a, 0x29, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x54, 0x65, 0x78,
	0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x4d, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x4e, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x03, 0x2a, 0x53, 0x0a, 0x2b, 0x54, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x54, 0x65, 0x78, 0x74, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4c, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x54, 0x41, 0x4c, 0x49, 0x43, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44,
	0x45, 0x52, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_attributes_proto_rawDescOnce sync.Once
	file_attributes_proto_rawDescData = file_attributes_proto_rawDesc
)

func file_attributes_proto_rawDescGZIP() []byte {
	file_attributes_proto_rawDescOnce.Do(func() {
		file_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_attributes_proto_rawDescData)
	})
	return file_attributes_proto_rawDescData
}

var file_attributes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_attributes_proto_goTypes = []interface{}{
	(TextMediaAttribute_TextMediaAttributeType)(0),   // 0: attributes.TextMediaAttribute_TextMediaAttributeType
	(TextFormatAttribute_TextFormatAttributeType)(0), // 1: attributes.TextFormatAttribute_TextFormatAttributeType
	(*TextAttribute)(nil),                            // 2: attributes.TextAttribute
	(*TextScaleAttribute)(nil),                       // 3: attributes.TextScaleAttribute
	(*MentionAttribute)(nil),                         // 4: attributes.MentionAttribute
	(*TextUrlAttribute)(nil),                         // 5: attributes.TextUrlAttribute
	(*TextMediaAttribute)(nil),                       // 6: attributes.TextMediaAttribute
	(*TextFormatAttribute)(nil),                      // 7: attributes.TextFormatAttribute
	(*Range)(nil),                                    // 8: common.Range
	(*UUID)(nil),                                     // 9: uuid.UUID
}
var file_attributes_proto_depIdxs = []int32{
	8, // 0: attributes.TextAttribute.range:type_name -> common.Range
	7, // 1: attributes.TextAttribute.formatAttribute:type_name -> attributes.TextFormatAttribute
	6, // 2: attributes.TextAttribute.mediaAttribute:type_name -> attributes.TextMediaAttribute
	5, // 3: attributes.TextAttribute.urlAttribute:type_name -> attributes.TextUrlAttribute
	4, // 4: attributes.TextAttribute.mention:type_name -> attributes.MentionAttribute
	3, // 5: attributes.TextAttribute.scaleAttribute:type_name -> attributes.TextScaleAttribute
	9, // 6: attributes.MentionAttribute.userId:type_name -> uuid.UUID
	0, // 7: attributes.TextMediaAttribute.textMediaAttributeType:type_name -> attributes.TextMediaAttribute_TextMediaAttributeType
	1, // 8: attributes.TextFormatAttribute.textFormatAttributeType:type_name -> attributes.TextFormatAttribute_TextFormatAttributeType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_attributes_proto_init() }
func file_attributes_proto_init() {
	if File_attributes_proto != nil {
		return
	}
	file_common_proto_init()
	file_uuid_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextScaleAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MentionAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextUrlAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextMediaAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextFormatAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_attributes_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TextAttribute_FormatAttribute)(nil),
		(*TextAttribute_MediaAttribute)(nil),
		(*TextAttribute_UrlAttribute)(nil),
		(*TextAttribute_Mention)(nil),
		(*TextAttribute_ScaleAttribute)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attributes_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attributes_proto_goTypes,
		DependencyIndexes: file_attributes_proto_depIdxs,
		EnumInfos:         file_attributes_proto_enumTypes,
		MessageInfos:      file_attributes_proto_msgTypes,
	}.Build()
	File_attributes_proto = out.File
	file_attributes_proto_rawDesc = nil
	file_attributes_proto_goTypes = nil
	file_attributes_proto_depIdxs = nil
}
