// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: blizzard.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncReason int32

const (
	SyncReason_UNSET             SyncReason = 0
	SyncReason_PAGE_LOAD         SyncReason = 1
	SyncReason_PAGE_FOCUS        SyncReason = 2
	SyncReason_ONLINE            SyncReason = 3
	SyncReason_VISIBILITY_CHANGE SyncReason = 4
)

// Enum value maps for SyncReason.
var (
	SyncReason_name = map[int32]string{
		0: "UNSET",
		1: "PAGE_LOAD",
		2: "PAGE_FOCUS",
		3: "ONLINE",
		4: "VISIBILITY_CHANGE",
	}
	SyncReason_value = map[string]int32{
		"UNSET":             0,
		"PAGE_LOAD":         1,
		"PAGE_FOCUS":        2,
		"ONLINE":            3,
		"VISIBILITY_CHANGE": 4,
	}
)

func (x SyncReason) Enum() *SyncReason {
	p := new(SyncReason)
	*p = x
	return p
}

func (x SyncReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncReason) Descriptor() protoreflect.EnumDescriptor {
	return file_blizzard_proto_enumTypes[0].Descriptor()
}

func (SyncReason) Type() protoreflect.EnumType {
	return &file_blizzard_proto_enumTypes[0]
}

func (x SyncReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncReason.Descriptor instead.
func (SyncReason) EnumDescriptor() ([]byte, []int) {
	return file_blizzard_proto_rawDescGZIP(), []int{0}
}

type ChatWallpaperBlizzardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatWallpaperSource int32 `protobuf:"varint,1,opt,name=chatWallpaperSource,proto3" json:"chatWallpaperSource,omitempty"`
}

func (x *ChatWallpaperBlizzardData) Reset() {
	*x = ChatWallpaperBlizzardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blizzard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatWallpaperBlizzardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatWallpaperBlizzardData) ProtoMessage() {}

func (x *ChatWallpaperBlizzardData) ProtoReflect() protoreflect.Message {
	mi := &file_blizzard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatWallpaperBlizzardData.ProtoReflect.Descriptor instead.
func (*ChatWallpaperBlizzardData) Descriptor() ([]byte, []int) {
	return file_blizzard_proto_rawDescGZIP(), []int{0}
}

func (x *ChatWallpaperBlizzardData) GetChatWallpaperSource() int32 {
	if x != nil {
		return x.ChatWallpaperSource
	}
	return 0
}

type SyncConversationsBlizzardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TivTransactionId string     `protobuf:"bytes,1,opt,name=tivTransactionId,proto3" json:"tivTransactionId,omitempty"`
	SyncReason       SyncReason `protobuf:"varint,2,opt,name=syncReason,proto3,enum=blizzard.SyncReason" json:"syncReason,omitempty"`
}

func (x *SyncConversationsBlizzardData) Reset() {
	*x = SyncConversationsBlizzardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blizzard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConversationsBlizzardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConversationsBlizzardData) ProtoMessage() {}

func (x *SyncConversationsBlizzardData) ProtoReflect() protoreflect.Message {
	mi := &file_blizzard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConversationsBlizzardData.ProtoReflect.Descriptor instead.
func (*SyncConversationsBlizzardData) Descriptor() ([]byte, []int) {
	return file_blizzard_proto_rawDescGZIP(), []int{1}
}

func (x *SyncConversationsBlizzardData) GetTivTransactionId() string {
	if x != nil {
		return x.TivTransactionId
	}
	return ""
}

func (x *SyncConversationsBlizzardData) GetSyncReason() SyncReason {
	if x != nil {
		return x.SyncReason
	}
	return SyncReason_UNSET
}

var File_blizzard_proto protoreflect.FileDescriptor

var file_blizzard_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x22, 0x4d, 0x0a, 0x19, 0x43, 0x68,
	0x61, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x70, 0x61, 0x70, 0x65, 0x72, 0x42, 0x6c, 0x69, 0x7a, 0x7a,
	0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x68, 0x61, 0x74, 0x57,
	0x61, 0x6c, 0x6c, 0x70, 0x61, 0x70, 0x65, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x63, 0x68, 0x61, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x1d, 0x53, 0x79,
	0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42,
	0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x10, 0x74,
	0x69, 0x76, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x69, 0x76, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x6c,
	0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x59, 0x0a,
	0x0a, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x55,
	0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x4c,
	0x4f, 0x41, 0x44, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x46, 0x4f,
	0x43, 0x55, 0x53, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10,
	0x03, 0x12, 0x15, 0x0a, 0x11, 0x56, 0x49, 0x53, 0x49, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x04, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blizzard_proto_rawDescOnce sync.Once
	file_blizzard_proto_rawDescData = file_blizzard_proto_rawDesc
)

func file_blizzard_proto_rawDescGZIP() []byte {
	file_blizzard_proto_rawDescOnce.Do(func() {
		file_blizzard_proto_rawDescData = protoimpl.X.CompressGZIP(file_blizzard_proto_rawDescData)
	})
	return file_blizzard_proto_rawDescData
}

var file_blizzard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blizzard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blizzard_proto_goTypes = []interface{}{
	(SyncReason)(0),                       // 0: blizzard.SyncReason
	(*ChatWallpaperBlizzardData)(nil),     // 1: blizzard.ChatWallpaperBlizzardData
	(*SyncConversationsBlizzardData)(nil), // 2: blizzard.SyncConversationsBlizzardData
}
var file_blizzard_proto_depIdxs = []int32{
	0, // 0: blizzard.SyncConversationsBlizzardData.syncReason:type_name -> blizzard.SyncReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blizzard_proto_init() }
func file_blizzard_proto_init() {
	if File_blizzard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blizzard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatWallpaperBlizzardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blizzard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConversationsBlizzardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blizzard_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blizzard_proto_goTypes,
		DependencyIndexes: file_blizzard_proto_depIdxs,
		EnumInfos:         file_blizzard_proto_enumTypes,
		MessageInfos:      file_blizzard_proto_msgTypes,
	}.Build()
	File_blizzard_proto = out.File
	file_blizzard_proto_rawDesc = nil
	file_blizzard_proto_goTypes = nil
	file_blizzard_proto_depIdxs = nil
}
