// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: caption.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptionMetadata_CaptionType int32

const (
	CaptionMetadata_CaptionType_DEFAULT        CaptionMetadata_CaptionType = 0
	CaptionMetadata_CaptionType_BIGTEXT_LEFT   CaptionMetadata_CaptionType = 1
	CaptionMetadata_CaptionType_BIGTEXT_CENTER CaptionMetadata_CaptionType = 2
	CaptionMetadata_CaptionType_BIGTEXT_RIGHT  CaptionMetadata_CaptionType = 3
)

// Enum value maps for CaptionMetadata_CaptionType.
var (
	CaptionMetadata_CaptionType_name = map[int32]string{
		0: "DEFAULT",
		1: "BIGTEXT_LEFT",
		2: "BIGTEXT_CENTER",
		3: "BIGTEXT_RIGHT",
	}
	CaptionMetadata_CaptionType_value = map[string]int32{
		"DEFAULT":        0,
		"BIGTEXT_LEFT":   1,
		"BIGTEXT_CENTER": 2,
		"BIGTEXT_RIGHT":  3,
	}
)

func (x CaptionMetadata_CaptionType) Enum() *CaptionMetadata_CaptionType {
	p := new(CaptionMetadata_CaptionType)
	*p = x
	return p
}

func (x CaptionMetadata_CaptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptionMetadata_CaptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_caption_proto_enumTypes[0].Descriptor()
}

func (CaptionMetadata_CaptionType) Type() protoreflect.EnumType {
	return &file_caption_proto_enumTypes[0]
}

func (x CaptionMetadata_CaptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptionMetadata_CaptionType.Descriptor instead.
func (CaptionMetadata_CaptionType) EnumDescriptor() ([]byte, []int) {
	return file_caption_proto_rawDescGZIP(), []int{0}
}

type CaptionMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FontSize float32                     `protobuf:"fixed32,1,opt,name=fontSize,proto3" json:"fontSize,omitempty"`
	CenterX  float32                     `protobuf:"fixed32,2,opt,name=centerX,proto3" json:"centerX,omitempty"`
	CenterY  float32                     `protobuf:"fixed32,3,opt,name=centerY,proto3" json:"centerY,omitempty"`
	Rotation float32                     `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Tracking bool                        `protobuf:"varint,5,opt,name=tracking,proto3" json:"tracking,omitempty"`
	Type     CaptionMetadata_CaptionType `protobuf:"varint,7,opt,name=type,proto3,enum=caption.CaptionMetadata_CaptionType" json:"type,omitempty"`
}

func (x *CaptionMetadata) Reset() {
	*x = CaptionMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caption_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptionMetadata) ProtoMessage() {}

func (x *CaptionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_caption_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptionMetadata.ProtoReflect.Descriptor instead.
func (*CaptionMetadata) Descriptor() ([]byte, []int) {
	return file_caption_proto_rawDescGZIP(), []int{0}
}

func (x *CaptionMetadata) GetFontSize() float32 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *CaptionMetadata) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *CaptionMetadata) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *CaptionMetadata) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *CaptionMetadata) GetTracking() bool {
	if x != nil {
		return x.Tracking
	}
	return false
}

func (x *CaptionMetadata) GetType() CaptionMetadata_CaptionType {
	if x != nil {
		return x.Type
	}
	return CaptionMetadata_CaptionType_DEFAULT
}

var File_caption_proto protoreflect.FileDescriptor

var file_caption_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd3, 0x01, 0x0a, 0x0f, 0x43, 0x61, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x6f, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x66, 0x6f, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x58, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x59, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x59, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x24, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x43, 0x61, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x63,
	0x0a, 0x1b, 0x43, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49,
	0x47, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x42, 0x49, 0x47, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x47, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_caption_proto_rawDescOnce sync.Once
	file_caption_proto_rawDescData = file_caption_proto_rawDesc
)

func file_caption_proto_rawDescGZIP() []byte {
	file_caption_proto_rawDescOnce.Do(func() {
		file_caption_proto_rawDescData = protoimpl.X.CompressGZIP(file_caption_proto_rawDescData)
	})
	return file_caption_proto_rawDescData
}

var file_caption_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_caption_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_caption_proto_goTypes = []interface{}{
	(CaptionMetadata_CaptionType)(0), // 0: caption.CaptionMetadata_CaptionType
	(*CaptionMetadata)(nil),          // 1: caption.CaptionMetadata
}
var file_caption_proto_depIdxs = []int32{
	0, // 0: caption.CaptionMetadata.type:type_name -> caption.CaptionMetadata_CaptionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_caption_proto_init() }
func file_caption_proto_init() {
	if File_caption_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caption_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptionMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caption_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_caption_proto_goTypes,
		DependencyIndexes: file_caption_proto_depIdxs,
		EnumInfos:         file_caption_proto_enumTypes,
		MessageInfos:      file_caption_proto_msgTypes,
	}.Build()
	File_caption_proto = out.File
	file_caption_proto_rawDesc = nil
	file_caption_proto_goTypes = nil
	file_caption_proto_depIdxs = nil
}
