// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: display.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusMessageDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Status:
	//
	//	*StatusMessageDisplayInfo_ScreenCapture
	//	*StatusMessageDisplayInfo_CallingStatus
	//	*StatusMessageDisplayInfo_ChangeParticipant
	//	*StatusMessageDisplayInfo_NameChange
	//	*StatusMessageDisplayInfo_SaveToCameraRoll
	//	*StatusMessageDisplayInfo_InMyContacts
	//	*StatusMessageDisplayInfo_GenericChat
	//	*StatusMessageDisplayInfo_KickParticipant
	//	*StatusMessageDisplayInfo_GroupCreated
	Status isStatusMessageDisplayInfo_Status `protobuf_oneof:"status"`
}

func (x *StatusMessageDisplayInfo) Reset() {
	*x = StatusMessageDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusMessageDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessageDisplayInfo) ProtoMessage() {}

func (x *StatusMessageDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessageDisplayInfo.ProtoReflect.Descriptor instead.
func (*StatusMessageDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{0}
}

func (m *StatusMessageDisplayInfo) GetStatus() isStatusMessageDisplayInfo_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetScreenCapture() *StatusScreenCaptureDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_ScreenCapture); ok {
		return x.ScreenCapture
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetCallingStatus() *StatusCallingStatusDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_CallingStatus); ok {
		return x.CallingStatus
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetChangeParticipant() *StatusParticipantAddDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_ChangeParticipant); ok {
		return x.ChangeParticipant
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetNameChange() *StatusNameChangeDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_NameChange); ok {
		return x.NameChange
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetSaveToCameraRoll() *StatusSaveToCameraRollDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_SaveToCameraRoll); ok {
		return x.SaveToCameraRoll
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetInMyContacts() *StatusInMyContactsDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_InMyContacts); ok {
		return x.InMyContacts
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetGenericChat() *StatusGenericChat {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_GenericChat); ok {
		return x.GenericChat
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetKickParticipant() *StatusParticipantKickDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_KickParticipant); ok {
		return x.KickParticipant
	}
	return nil
}

func (x *StatusMessageDisplayInfo) GetGroupCreated() *StatusGroupChatCreatedDisplayInfo {
	if x, ok := x.GetStatus().(*StatusMessageDisplayInfo_GroupCreated); ok {
		return x.GroupCreated
	}
	return nil
}

type isStatusMessageDisplayInfo_Status interface {
	isStatusMessageDisplayInfo_Status()
}

type StatusMessageDisplayInfo_ScreenCapture struct {
	ScreenCapture *StatusScreenCaptureDisplayInfo `protobuf:"bytes,1,opt,name=screenCapture,proto3,oneof"`
}

type StatusMessageDisplayInfo_CallingStatus struct {
	CallingStatus *StatusCallingStatusDisplayInfo `protobuf:"bytes,2,opt,name=callingStatus,proto3,oneof"`
}

type StatusMessageDisplayInfo_ChangeParticipant struct {
	ChangeParticipant *StatusParticipantAddDisplayInfo `protobuf:"bytes,3,opt,name=changeParticipant,proto3,oneof"`
}

type StatusMessageDisplayInfo_NameChange struct {
	NameChange *StatusNameChangeDisplayInfo `protobuf:"bytes,4,opt,name=nameChange,proto3,oneof"`
}

type StatusMessageDisplayInfo_SaveToCameraRoll struct {
	SaveToCameraRoll *StatusSaveToCameraRollDisplayInfo `protobuf:"bytes,5,opt,name=saveToCameraRoll,proto3,oneof"`
}

type StatusMessageDisplayInfo_InMyContacts struct {
	InMyContacts *StatusInMyContactsDisplayInfo `protobuf:"bytes,6,opt,name=inMyContacts,proto3,oneof"`
}

type StatusMessageDisplayInfo_GenericChat struct {
	GenericChat *StatusGenericChat `protobuf:"bytes,7,opt,name=genericChat,proto3,oneof"`
}

type StatusMessageDisplayInfo_KickParticipant struct {
	KickParticipant *StatusParticipantKickDisplayInfo `protobuf:"bytes,8,opt,name=kickParticipant,proto3,oneof"`
}

type StatusMessageDisplayInfo_GroupCreated struct {
	GroupCreated *StatusGroupChatCreatedDisplayInfo `protobuf:"bytes,9,opt,name=groupCreated,proto3,oneof"`
}

func (*StatusMessageDisplayInfo_ScreenCapture) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_CallingStatus) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_ChangeParticipant) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_NameChange) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_SaveToCameraRoll) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_InMyContacts) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_GenericChat) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_KickParticipant) isStatusMessageDisplayInfo_Status() {}

func (*StatusMessageDisplayInfo_GroupCreated) isStatusMessageDisplayInfo_Status() {}

type ShareDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Share:
	//
	//	*ShareDisplayInfo_SavedStory
	Share isShareDisplayInfo_Share `protobuf_oneof:"share"`
}

func (x *ShareDisplayInfo) Reset() {
	*x = ShareDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDisplayInfo) ProtoMessage() {}

func (x *ShareDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDisplayInfo.ProtoReflect.Descriptor instead.
func (*ShareDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{1}
}

func (m *ShareDisplayInfo) GetShare() isShareDisplayInfo_Share {
	if m != nil {
		return m.Share
	}
	return nil
}

func (x *ShareDisplayInfo) GetSavedStory() *ShareSavedStoryDisplayInfo {
	if x, ok := x.GetShare().(*ShareDisplayInfo_SavedStory); ok {
		return x.SavedStory
	}
	return nil
}

type isShareDisplayInfo_Share interface {
	isShareDisplayInfo_Share()
}

type ShareDisplayInfo_SavedStory struct {
	SavedStory *ShareSavedStoryDisplayInfo `protobuf:"bytes,1,opt,name=savedStory,proto3,oneof"`
}

func (*ShareDisplayInfo_SavedStory) isShareDisplayInfo_Share() {}

type ShareSavedStoryDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasAudio bool `protobuf:"varint,1,opt,name=hasAudio,proto3" json:"hasAudio,omitempty"`
}

func (x *ShareSavedStoryDisplayInfo) Reset() {
	*x = ShareSavedStoryDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareSavedStoryDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareSavedStoryDisplayInfo) ProtoMessage() {}

func (x *ShareSavedStoryDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareSavedStoryDisplayInfo.ProtoReflect.Descriptor instead.
func (*ShareSavedStoryDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{2}
}

func (x *ShareSavedStoryDisplayInfo) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

type SnapDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasAudio    bool `protobuf:"varint,1,opt,name=hasAudio,proto3" json:"hasAudio,omitempty"`
	NotViewable bool `protobuf:"varint,2,opt,name=notViewable,proto3" json:"notViewable,omitempty"`
}

func (x *SnapDisplayInfo) Reset() {
	*x = SnapDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapDisplayInfo) ProtoMessage() {}

func (x *SnapDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapDisplayInfo.ProtoReflect.Descriptor instead.
func (*SnapDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{3}
}

func (x *SnapDisplayInfo) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

func (x *SnapDisplayInfo) GetNotViewable() bool {
	if x != nil {
		return x.NotViewable
	}
	return false
}

type ExternalMediaDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Media:
	//
	//	*ExternalMediaDisplayInfo_Default
	//	*ExternalMediaDisplayInfo_Gift
	Media isExternalMediaDisplayInfo_Media `protobuf_oneof:"media"`
}

func (x *ExternalMediaDisplayInfo) Reset() {
	*x = ExternalMediaDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMediaDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMediaDisplayInfo) ProtoMessage() {}

func (x *ExternalMediaDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMediaDisplayInfo.ProtoReflect.Descriptor instead.
func (*ExternalMediaDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{4}
}

func (m *ExternalMediaDisplayInfo) GetMedia() isExternalMediaDisplayInfo_Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (x *ExternalMediaDisplayInfo) GetDefault() *ExternalMediaDefaultDisplayInfo {
	if x, ok := x.GetMedia().(*ExternalMediaDisplayInfo_Default); ok {
		return x.Default
	}
	return nil
}

func (x *ExternalMediaDisplayInfo) GetGift() *ExternalMediaGiftDisplayInfo {
	if x, ok := x.GetMedia().(*ExternalMediaDisplayInfo_Gift); ok {
		return x.Gift
	}
	return nil
}

type isExternalMediaDisplayInfo_Media interface {
	isExternalMediaDisplayInfo_Media()
}

type ExternalMediaDisplayInfo_Default struct {
	Default *ExternalMediaDefaultDisplayInfo `protobuf:"bytes,1,opt,name=default,proto3,oneof"`
}

type ExternalMediaDisplayInfo_Gift struct {
	Gift *ExternalMediaGiftDisplayInfo `protobuf:"bytes,2,opt,name=gift,proto3,oneof"`
}

func (*ExternalMediaDisplayInfo_Default) isExternalMediaDisplayInfo_Media() {}

func (*ExternalMediaDisplayInfo_Gift) isExternalMediaDisplayInfo_Media() {}

type ExternalMediaDefaultDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExternalMediaDefaultDisplayInfo) Reset() {
	*x = ExternalMediaDefaultDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMediaDefaultDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMediaDefaultDisplayInfo) ProtoMessage() {}

func (x *ExternalMediaDefaultDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMediaDefaultDisplayInfo.ProtoReflect.Descriptor instead.
func (*ExternalMediaDefaultDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{5}
}

type ExternalMediaGiftDisplayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExternalMediaGiftDisplayInfo) Reset() {
	*x = ExternalMediaGiftDisplayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMediaGiftDisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMediaGiftDisplayInfo) ProtoMessage() {}

func (x *ExternalMediaGiftDisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMediaGiftDisplayInfo.ProtoReflect.Descriptor instead.
func (*ExternalMediaGiftDisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{6}
}

var File_display_proto protoreflect.FileDescriptor

var file_display_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x1a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x05, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x4e, 0x0a, 0x0d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x43, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x43, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x57, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0a,
	0x6e, 0x61, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x73, 0x61, 0x76, 0x65, 0x54, 0x6f, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x52, 0x6f, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x61, 0x76,
	0x65, 0x54, 0x6f, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x6f, 0x6c, 0x6c, 0x44, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x10, 0x73, 0x61, 0x76, 0x65,
	0x54, 0x6f, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x6f, 0x6c, 0x6c, 0x12, 0x4b, 0x0a, 0x0c,
	0x69, 0x6e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x49, 0x6e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x44, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x4d,
	0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x43, 0x68, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x69, 0x63, 0x43, 0x68, 0x61, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x43, 0x68, 0x61, 0x74, 0x12, 0x54, 0x0a, 0x0f, 0x6b, 0x69, 0x63, 0x6b,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4b, 0x69, 0x63, 0x6b,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0f, 0x6b,
	0x69, 0x63, 0x6b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x12, 0x4f,
	0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x08, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x62, 0x0a, 0x10, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x45, 0x0a,
	0x0a, 0x73, 0x61, 0x76, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x53, 0x61, 0x76, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x64, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x38, 0x0a,
	0x1a, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x61, 0x76, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x79,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x61, 0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x4f, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x70, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61,
	0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61,
	0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x56, 0x69, 0x65,
	0x77, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x6f, 0x74,
	0x56, 0x69, 0x65, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x18, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x04, 0x67,
	0x69, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x47, 0x69, 0x66, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x48, 0x00, 0x52, 0x04, 0x67, 0x69, 0x66, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x22, 0x21, 0x0a, 0x1f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1e, 0x0a, 0x1c, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x47, 0x69, 0x66, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_display_proto_rawDescOnce sync.Once
	file_display_proto_rawDescData = file_display_proto_rawDesc
)

func file_display_proto_rawDescGZIP() []byte {
	file_display_proto_rawDescOnce.Do(func() {
		file_display_proto_rawDescData = protoimpl.X.CompressGZIP(file_display_proto_rawDescData)
	})
	return file_display_proto_rawDescData
}

var file_display_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_display_proto_goTypes = []interface{}{
	(*StatusMessageDisplayInfo)(nil),          // 0: display.StatusMessageDisplayInfo
	(*ShareDisplayInfo)(nil),                  // 1: display.ShareDisplayInfo
	(*ShareSavedStoryDisplayInfo)(nil),        // 2: display.ShareSavedStoryDisplayInfo
	(*SnapDisplayInfo)(nil),                   // 3: display.SnapDisplayInfo
	(*ExternalMediaDisplayInfo)(nil),          // 4: display.ExternalMediaDisplayInfo
	(*ExternalMediaDefaultDisplayInfo)(nil),   // 5: display.ExternalMediaDefaultDisplayInfo
	(*ExternalMediaGiftDisplayInfo)(nil),      // 6: display.ExternalMediaGiftDisplayInfo
	(*StatusScreenCaptureDisplayInfo)(nil),    // 7: status.StatusScreenCaptureDisplayInfo
	(*StatusCallingStatusDisplayInfo)(nil),    // 8: status.StatusCallingStatusDisplayInfo
	(*StatusParticipantAddDisplayInfo)(nil),   // 9: status.StatusParticipantAddDisplayInfo
	(*StatusNameChangeDisplayInfo)(nil),       // 10: status.StatusNameChangeDisplayInfo
	(*StatusSaveToCameraRollDisplayInfo)(nil), // 11: status.StatusSaveToCameraRollDisplayInfo
	(*StatusInMyContactsDisplayInfo)(nil),     // 12: status.StatusInMyContactsDisplayInfo
	(*StatusGenericChat)(nil),                 // 13: status.StatusGenericChat
	(*StatusParticipantKickDisplayInfo)(nil),  // 14: status.StatusParticipantKickDisplayInfo
	(*StatusGroupChatCreatedDisplayInfo)(nil), // 15: status.StatusGroupChatCreatedDisplayInfo
}
var file_display_proto_depIdxs = []int32{
	7,  // 0: display.StatusMessageDisplayInfo.screenCapture:type_name -> status.StatusScreenCaptureDisplayInfo
	8,  // 1: display.StatusMessageDisplayInfo.callingStatus:type_name -> status.StatusCallingStatusDisplayInfo
	9,  // 2: display.StatusMessageDisplayInfo.changeParticipant:type_name -> status.StatusParticipantAddDisplayInfo
	10, // 3: display.StatusMessageDisplayInfo.nameChange:type_name -> status.StatusNameChangeDisplayInfo
	11, // 4: display.StatusMessageDisplayInfo.saveToCameraRoll:type_name -> status.StatusSaveToCameraRollDisplayInfo
	12, // 5: display.StatusMessageDisplayInfo.inMyContacts:type_name -> status.StatusInMyContactsDisplayInfo
	13, // 6: display.StatusMessageDisplayInfo.genericChat:type_name -> status.StatusGenericChat
	14, // 7: display.StatusMessageDisplayInfo.kickParticipant:type_name -> status.StatusParticipantKickDisplayInfo
	15, // 8: display.StatusMessageDisplayInfo.groupCreated:type_name -> status.StatusGroupChatCreatedDisplayInfo
	2,  // 9: display.ShareDisplayInfo.savedStory:type_name -> display.ShareSavedStoryDisplayInfo
	5,  // 10: display.ExternalMediaDisplayInfo.default:type_name -> display.ExternalMediaDefaultDisplayInfo
	6,  // 11: display.ExternalMediaDisplayInfo.gift:type_name -> display.ExternalMediaGiftDisplayInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_display_proto_init() }
func file_display_proto_init() {
	if File_display_proto != nil {
		return
	}
	file_status_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_display_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusMessageDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareSavedStoryDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMediaDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMediaDefaultDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMediaGiftDisplayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_display_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StatusMessageDisplayInfo_ScreenCapture)(nil),
		(*StatusMessageDisplayInfo_CallingStatus)(nil),
		(*StatusMessageDisplayInfo_ChangeParticipant)(nil),
		(*StatusMessageDisplayInfo_NameChange)(nil),
		(*StatusMessageDisplayInfo_SaveToCameraRoll)(nil),
		(*StatusMessageDisplayInfo_InMyContacts)(nil),
		(*StatusMessageDisplayInfo_GenericChat)(nil),
		(*StatusMessageDisplayInfo_KickParticipant)(nil),
		(*StatusMessageDisplayInfo_GroupCreated)(nil),
	}
	file_display_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ShareDisplayInfo_SavedStory)(nil),
	}
	file_display_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ExternalMediaDisplayInfo_Default)(nil),
		(*ExternalMediaDisplayInfo_Gift)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_display_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_display_proto_goTypes,
		DependencyIndexes: file_display_proto_depIdxs,
		MessageInfos:      file_display_proto_msgTypes,
	}.Build()
	File_display_proto = out.File
	file_display_proto_rawDesc = nil
	file_display_proto_goTypes = nil
	file_display_proto_depIdxs = nil
}
