// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: fidelius.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FideliusTentativeWebKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UncompressedPubkey []byte `protobuf:"bytes,1,opt,name=uncompressedPubkey,proto3" json:"uncompressedPubkey,omitempty"` // EC public key uncompressed
	KeyPairId          []byte `protobuf:"bytes,2,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`                   // HMAC_SHA256_HASH (identity key)
	Rwk                []byte `protobuf:"bytes,3,opt,name=rwk,proto3" json:"rwk,omitempty"`                               // HMAC_SHA256_KEY
	Version            uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *FideliusTentativeWebKey) Reset() {
	*x = FideliusTentativeWebKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fidelius_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FideliusTentativeWebKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FideliusTentativeWebKey) ProtoMessage() {}

func (x *FideliusTentativeWebKey) ProtoReflect() protoreflect.Message {
	mi := &file_fidelius_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FideliusTentativeWebKey.ProtoReflect.Descriptor instead.
func (*FideliusTentativeWebKey) Descriptor() ([]byte, []int) {
	return file_fidelius_proto_rawDescGZIP(), []int{0}
}

func (x *FideliusTentativeWebKey) GetUncompressedPubkey() []byte {
	if x != nil {
		return x.UncompressedPubkey
	}
	return nil
}

func (x *FideliusTentativeWebKey) GetKeyPairId() []byte {
	if x != nil {
		return x.KeyPairId
	}
	return nil
}

func (x *FideliusTentativeWebKey) GetRwk() []byte {
	if x != nil {
		return x.Rwk
	}
	return nil
}

func (x *FideliusTentativeWebKey) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type FideliusGetFriendKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FideliusGetFriendKeys) Reset() {
	*x = FideliusGetFriendKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fidelius_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FideliusGetFriendKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FideliusGetFriendKeys) ProtoMessage() {}

func (x *FideliusGetFriendKeys) ProtoReflect() protoreflect.Message {
	mi := &file_fidelius_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FideliusGetFriendKeys.ProtoReflect.Descriptor instead.
func (*FideliusGetFriendKeys) Descriptor() ([]byte, []int) {
	return file_fidelius_proto_rawDescGZIP(), []int{1}
}

var File_fidelius_proto protoreflect.FileDescriptor

var file_fidelius_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x66, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x75, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x46,
	0x69, 0x64, 0x65, 0x6c, 0x69, 0x75, 0x73, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x12, 0x75, 0x6e, 0x63, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x12, 0x75, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61,
	0x69, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x77, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x72, 0x77, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x17, 0x0a, 0x15, 0x46, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x75, 0x73, 0x47, 0x65, 0x74, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fidelius_proto_rawDescOnce sync.Once
	file_fidelius_proto_rawDescData = file_fidelius_proto_rawDesc
)

func file_fidelius_proto_rawDescGZIP() []byte {
	file_fidelius_proto_rawDescOnce.Do(func() {
		file_fidelius_proto_rawDescData = protoimpl.X.CompressGZIP(file_fidelius_proto_rawDescData)
	})
	return file_fidelius_proto_rawDescData
}

var file_fidelius_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fidelius_proto_goTypes = []interface{}{
	(*FideliusTentativeWebKey)(nil), // 0: fidelius.FideliusTentativeWebKey
	(*FideliusGetFriendKeys)(nil),   // 1: fidelius.FideliusGetFriendKeys
}
var file_fidelius_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fidelius_proto_init() }
func file_fidelius_proto_init() {
	if File_fidelius_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fidelius_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FideliusTentativeWebKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fidelius_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FideliusGetFriendKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fidelius_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fidelius_proto_goTypes,
		DependencyIndexes: file_fidelius_proto_depIdxs,
		MessageInfos:      file_fidelius_proto_msgTypes,
	}.Build()
	File_fidelius_proto = out.File
	file_fidelius_proto_rawDesc = nil
	file_fidelius_proto_goTypes = nil
	file_fidelius_proto_depIdxs = nil
}
