// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: gifts.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GiftInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderReferenceId *UUID `protobuf:"bytes,1,opt,name=orderReferenceId,proto3" json:"orderReferenceId,omitempty"`
	GiftId           *UUID `protobuf:"bytes,2,opt,name=giftId,proto3" json:"giftId,omitempty"`
}

func (x *GiftInfo) Reset() {
	*x = GiftInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftInfo) ProtoMessage() {}

func (x *GiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftInfo.ProtoReflect.Descriptor instead.
func (*GiftInfo) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{0}
}

func (x *GiftInfo) GetOrderReferenceId() *UUID {
	if x != nil {
		return x.OrderReferenceId
	}
	return nil
}

func (x *GiftInfo) GetGiftId() *UUID {
	if x != nil {
		return x.GiftId
	}
	return nil
}

var File_gifts_proto protoreflect.FileDescriptor

var file_gifts_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x69, 0x66, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x69, 0x66, 0x74, 0x73, 0x1a, 0x0a, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x66, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x10,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x55, 0x55,
	0x49, 0x44, 0x52, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x06, 0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gifts_proto_rawDescOnce sync.Once
	file_gifts_proto_rawDescData = file_gifts_proto_rawDesc
)

func file_gifts_proto_rawDescGZIP() []byte {
	file_gifts_proto_rawDescOnce.Do(func() {
		file_gifts_proto_rawDescData = protoimpl.X.CompressGZIP(file_gifts_proto_rawDescData)
	})
	return file_gifts_proto_rawDescData
}

var file_gifts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gifts_proto_goTypes = []interface{}{
	(*GiftInfo)(nil), // 0: gifts.GiftInfo
	(*UUID)(nil),     // 1: uuid.UUID
}
var file_gifts_proto_depIdxs = []int32{
	1, // 0: gifts.GiftInfo.orderReferenceId:type_name -> uuid.UUID
	1, // 1: gifts.GiftInfo.giftId:type_name -> uuid.UUID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gifts_proto_init() }
func file_gifts_proto_init() {
	if File_gifts_proto != nil {
		return
	}
	file_uuid_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gifts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gifts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gifts_proto_goTypes,
		DependencyIndexes: file_gifts_proto_depIdxs,
		MessageInfos:      file_gifts_proto_msgTypes,
	}.Build()
	File_gifts_proto = out.File
	file_gifts_proto_rawDesc = nil
	file_gifts_proto_goTypes = nil
	file_gifts_proto_depIdxs = nil
}
