// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: initializeWebKey.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializeWebKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnDeviceKeyPairIds [][]byte                 `protobuf:"bytes,1,rep,name=onDeviceKeyPairIds,proto3" json:"onDeviceKeyPairIds,omitempty"`
	TentativeWebKey    *FideliusTentativeWebKey `protobuf:"bytes,2,opt,name=tentativeWebKey,proto3" json:"tentativeWebKey,omitempty"`
}

func (x *InitializeWebKeyRequest) Reset() {
	*x = InitializeWebKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_initializeWebKey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeWebKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeWebKeyRequest) ProtoMessage() {}

func (x *InitializeWebKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_initializeWebKey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeWebKeyRequest.ProtoReflect.Descriptor instead.
func (*InitializeWebKeyRequest) Descriptor() ([]byte, []int) {
	return file_initializeWebKey_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeWebKeyRequest) GetOnDeviceKeyPairIds() [][]byte {
	if x != nil {
		return x.OnDeviceKeyPairIds
	}
	return nil
}

func (x *InitializeWebKeyRequest) GetTentativeWebKey() *FideliusTentativeWebKey {
	if x != nil {
		return x.TentativeWebKey
	}
	return nil
}

type InitializeWebKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rwk       []byte `protobuf:"bytes,1,opt,name=rwk,proto3" json:"rwk,omitempty"`
	KeyPairId []byte `protobuf:"bytes,2,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
}

func (x *InitializeWebKeyResponse) Reset() {
	*x = InitializeWebKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_initializeWebKey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeWebKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeWebKeyResponse) ProtoMessage() {}

func (x *InitializeWebKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_initializeWebKey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeWebKeyResponse.ProtoReflect.Descriptor instead.
func (*InitializeWebKeyResponse) Descriptor() ([]byte, []int) {
	return file_initializeWebKey_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeWebKeyResponse) GetRwk() []byte {
	if x != nil {
		return x.Rwk
	}
	return nil
}

func (x *InitializeWebKeyResponse) GetKeyPairId() []byte {
	if x != nil {
		return x.KeyPairId
	}
	return nil
}

var File_initializeWebKey_proto protoreflect.FileDescriptor

var file_initializeWebKey_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x57, 0x65, 0x62, 0x4b,
	0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x1a, 0x0e, 0x66, 0x69, 0x64, 0x65,
	0x6c, 0x69, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x17, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x6f, 0x6e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x12, 0x6f, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x50,
	0x61, 0x69, 0x72, 0x49, 0x64, 0x73, 0x12, 0x4b, 0x0a, 0x0f, 0x74, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x66, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x75, 0x73, 0x2e, 0x46, 0x69, 0x64, 0x65, 0x6c,
	0x69, 0x75, 0x73, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x76, 0x65, 0x57, 0x65, 0x62, 0x4b,
	0x65, 0x79, 0x52, 0x0f, 0x74, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x76, 0x65, 0x57, 0x65, 0x62,
	0x4b, 0x65, 0x79, 0x22, 0x4a, 0x0a, 0x18, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x77, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x77,
	0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_initializeWebKey_proto_rawDescOnce sync.Once
	file_initializeWebKey_proto_rawDescData = file_initializeWebKey_proto_rawDesc
)

func file_initializeWebKey_proto_rawDescGZIP() []byte {
	file_initializeWebKey_proto_rawDescOnce.Do(func() {
		file_initializeWebKey_proto_rawDescData = protoimpl.X.CompressGZIP(file_initializeWebKey_proto_rawDescData)
	})
	return file_initializeWebKey_proto_rawDescData
}

var file_initializeWebKey_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_initializeWebKey_proto_goTypes = []interface{}{
	(*InitializeWebKeyRequest)(nil),  // 0: initializeWebKey.InitializeWebKeyRequest
	(*InitializeWebKeyResponse)(nil), // 1: initializeWebKey.InitializeWebKeyResponse
	(*FideliusTentativeWebKey)(nil),  // 2: fidelius.FideliusTentativeWebKey
}
var file_initializeWebKey_proto_depIdxs = []int32{
	2, // 0: initializeWebKey.InitializeWebKeyRequest.tentativeWebKey:type_name -> fidelius.FideliusTentativeWebKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_initializeWebKey_proto_init() }
func file_initializeWebKey_proto_init() {
	if File_initializeWebKey_proto != nil {
		return
	}
	file_fidelius_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_initializeWebKey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeWebKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_initializeWebKey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeWebKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_initializeWebKey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_initializeWebKey_proto_goTypes,
		DependencyIndexes: file_initializeWebKey_proto_depIdxs,
		MessageInfos:      file_initializeWebKey_proto_msgTypes,
	}.Build()
	File_initializeWebKey_proto = out.File
	file_initializeWebKey_proto_rawDesc = nil
	file_initializeWebKey_proto_goTypes = nil
	file_initializeWebKey_proto_depIdxs = nil
}
