// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: policy.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapPostOpenViewingPolicy int32

const (
	SnapPostOpenViewingPolicy_POLICY_UNSET_OR_ENVELOPE SnapPostOpenViewingPolicy = 0
	SnapPostOpenViewingPolicy_POLICY_MEDIA             SnapPostOpenViewingPolicy = 1
)

// Enum value maps for SnapPostOpenViewingPolicy.
var (
	SnapPostOpenViewingPolicy_name = map[int32]string{
		0: "POLICY_UNSET_OR_ENVELOPE",
		1: "POLICY_MEDIA",
	}
	SnapPostOpenViewingPolicy_value = map[string]int32{
		"POLICY_UNSET_OR_ENVELOPE": 0,
		"POLICY_MEDIA":             1,
	}
)

func (x SnapPostOpenViewingPolicy) Enum() *SnapPostOpenViewingPolicy {
	p := new(SnapPostOpenViewingPolicy)
	*p = x
	return p
}

func (x SnapPostOpenViewingPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapPostOpenViewingPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[0].Descriptor()
}

func (SnapPostOpenViewingPolicy) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[0]
}

func (x SnapPostOpenViewingPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapPostOpenViewingPolicy.Descriptor instead.
func (SnapPostOpenViewingPolicy) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

type ContentSenderLeavePolicy int32

const (
	ContentSenderLeavePolicy_REMOVE ContentSenderLeavePolicy = 0
	ContentSenderLeavePolicy_KEEP   ContentSenderLeavePolicy = 1
)

// Enum value maps for ContentSenderLeavePolicy.
var (
	ContentSenderLeavePolicy_name = map[int32]string{
		0: "REMOVE",
		1: "KEEP",
	}
	ContentSenderLeavePolicy_value = map[string]int32{
		"REMOVE": 0,
		"KEEP":   1,
	}
)

func (x ContentSenderLeavePolicy) Enum() *ContentSenderLeavePolicy {
	p := new(ContentSenderLeavePolicy)
	*p = x
	return p
}

func (x ContentSenderLeavePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentSenderLeavePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[1].Descriptor()
}

func (ContentSenderLeavePolicy) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[1]
}

func (x ContentSenderLeavePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentSenderLeavePolicy.Descriptor instead.
func (ContentSenderLeavePolicy) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

type ContentReadReleasePolicy int32

const (
	ContentReadReleasePolicy_HIGH_WATER_MARK                   ContentReadReleasePolicy = 0
	ContentReadReleasePolicy_PER_MESSAGE                       ContentReadReleasePolicy = 1
	ContentReadReleasePolicy_SNAP                              ContentReadReleasePolicy = 2
	ContentReadReleasePolicy_HIGH_WATER_MARK_REQUESTED_MESSAGE ContentReadReleasePolicy = 3
)

// Enum value maps for ContentReadReleasePolicy.
var (
	ContentReadReleasePolicy_name = map[int32]string{
		0: "HIGH_WATER_MARK",
		1: "PER_MESSAGE",
		2: "SNAP",
		3: "HIGH_WATER_MARK_REQUESTED_MESSAGE",
	}
	ContentReadReleasePolicy_value = map[string]int32{
		"HIGH_WATER_MARK":                   0,
		"PER_MESSAGE":                       1,
		"SNAP":                              2,
		"HIGH_WATER_MARK_REQUESTED_MESSAGE": 3,
	}
)

func (x ContentReadReleasePolicy) Enum() *ContentReadReleasePolicy {
	p := new(ContentReadReleasePolicy)
	*p = x
	return p
}

func (x ContentReadReleasePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentReadReleasePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[2].Descriptor()
}

func (ContentReadReleasePolicy) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[2]
}

func (x ContentReadReleasePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentReadReleasePolicy.Descriptor instead.
func (ContentReadReleasePolicy) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

type RetentionPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Policy:
	//
	//	*RetentionPolicy_Dynamic
	Policy isRetentionPolicy_Policy `protobuf_oneof:"policy"`
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (m *RetentionPolicy) GetPolicy() isRetentionPolicy_Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (x *RetentionPolicy) GetDynamic() *DynamicRetentionPolicy {
	if x, ok := x.GetPolicy().(*RetentionPolicy_Dynamic); ok {
		return x.Dynamic
	}
	return nil
}

type isRetentionPolicy_Policy interface {
	isRetentionPolicy_Policy()
}

type RetentionPolicy_Dynamic struct {
	Dynamic *DynamicRetentionPolicy `protobuf:"bytes,1,opt,name=dynamic,proto3,oneof"`
}

func (*RetentionPolicy_Dynamic) isRetentionPolicy_Policy() {}

type DynamicRetentionPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendReadMessages           bool  `protobuf:"varint,1,opt,name=sendReadMessages,proto3" json:"sendReadMessages,omitempty"`
	SendReleaseMessages        bool  `protobuf:"varint,2,opt,name=sendReleaseMessages,proto3" json:"sendReleaseMessages,omitempty"`
	UnreadRetentionTimeSeconds int64 `protobuf:"varint,3,opt,name=unreadRetentionTimeSeconds,proto3" json:"unreadRetentionTimeSeconds,omitempty"`
	ReadRetentionTimeSeconds   int64 `protobuf:"varint,4,opt,name=readRetentionTimeSeconds,proto3" json:"readRetentionTimeSeconds,omitempty"`
}

func (x *DynamicRetentionPolicy) Reset() {
	*x = DynamicRetentionPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicRetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicRetentionPolicy) ProtoMessage() {}

func (x *DynamicRetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicRetentionPolicy.ProtoReflect.Descriptor instead.
func (*DynamicRetentionPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicRetentionPolicy) GetSendReadMessages() bool {
	if x != nil {
		return x.SendReadMessages
	}
	return false
}

func (x *DynamicRetentionPolicy) GetSendReleaseMessages() bool {
	if x != nil {
		return x.SendReleaseMessages
	}
	return false
}

func (x *DynamicRetentionPolicy) GetUnreadRetentionTimeSeconds() int64 {
	if x != nil {
		return x.UnreadRetentionTimeSeconds
	}
	return 0
}

func (x *DynamicRetentionPolicy) GetReadRetentionTimeSeconds() int64 {
	if x != nil {
		return x.ReadRetentionTimeSeconds
	}
	return 0
}

var File_policy_proto protoreflect.FileDescriptor

var file_policy_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x57, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x3a, 0x0a, 0x07, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x74, 0x65, 0x6e,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x00, 0x52, 0x07, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22,
	0xf2, 0x01, 0x0a, 0x16, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x74, 0x65, 0x6e,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x1a, 0x75, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x3a, 0x0a, 0x18, 0x72, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x18, 0x72, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x2a, 0x4b, 0x0a, 0x19, 0x53, 0x6e, 0x61, 0x70, 0x50, 0x6f, 0x73, 0x74,
	0x4f, 0x70, 0x65, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x45,
	0x54, 0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x4e, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x10,
	0x01, 0x2a, 0x30, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x45, 0x45,
	0x50, 0x10, 0x01, 0x2a, 0x71, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12,
	0x13, 0x0a, 0x0f, 0x48, 0x49, 0x47, 0x48, 0x5f, 0x57, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x41,
	0x52, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4e, 0x41, 0x50, 0x10, 0x02, 0x12,
	0x25, 0x0a, 0x21, 0x48, 0x49, 0x47, 0x48, 0x5f, 0x57, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x41,
	0x52, 0x4b, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData = file_policy_proto_rawDesc
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_policy_proto_rawDescData)
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_policy_proto_goTypes = []interface{}{
	(SnapPostOpenViewingPolicy)(0), // 0: policy.SnapPostOpenViewingPolicy
	(ContentSenderLeavePolicy)(0),  // 1: policy.ContentSenderLeavePolicy
	(ContentReadReleasePolicy)(0),  // 2: policy.ContentReadReleasePolicy
	(*RetentionPolicy)(nil),        // 3: policy.RetentionPolicy
	(*DynamicRetentionPolicy)(nil), // 4: policy.DynamicRetentionPolicy
}
var file_policy_proto_depIdxs = []int32{
	4, // 0: policy.RetentionPolicy.dynamic:type_name -> policy.DynamicRetentionPolicy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetentionPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicRetentionPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_policy_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RetentionPolicy_Dynamic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_policy_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		EnumInfos:         file_policy_proto_enumTypes,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_rawDesc = nil
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
