// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: queryMessages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// THIS IS ALSO THE CURSOR, YOU FETCH NEW MESSAGES BY SUPPLYING THE CONVERSATION VERSION RELATIVE TO THE LATEST MESSAGES YOU WOULD LIKE TO FETCH
	CurrentVersion     int64 `protobuf:"varint,1,opt,name=currentVersion,proto3" json:"currentVersion,omitempty"`
	ConversationId     *UUID `protobuf:"bytes,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	RequestedCountSize int32 `protobuf:"varint,3,opt,name=requestedCountSize,proto3" json:"requestedCountSize,omitempty"` // MAX 100
	SelfUserId         *UUID `protobuf:"bytes,4,opt,name=selfUserId,proto3" json:"selfUserId,omitempty"`
}

func (x *QueryMessagesRequest) Reset() {
	*x = QueryMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queryMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessagesRequest) ProtoMessage() {}

func (x *QueryMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queryMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessagesRequest.ProtoReflect.Descriptor instead.
func (*QueryMessagesRequest) Descriptor() ([]byte, []int) {
	return file_queryMessages_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMessagesRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *QueryMessagesRequest) GetConversationId() *UUID {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *QueryMessagesRequest) GetRequestedCountSize() int32 {
	if x != nil {
		return x.RequestedCountSize
	}
	return 0
}

func (x *QueryMessagesRequest) GetSelfUserId() *UUID {
	if x != nil {
		return x.SelfUserId
	}
	return nil
}

type QueryMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ContentMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NoMore   bool              `protobuf:"varint,2,opt,name=noMore,proto3" json:"noMore,omitempty"`
}

func (x *QueryMessagesResponse) Reset() {
	*x = QueryMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queryMessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessagesResponse) ProtoMessage() {}

func (x *QueryMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queryMessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessagesResponse.ProtoReflect.Descriptor instead.
func (*QueryMessagesResponse) Descriptor() ([]byte, []int) {
	return file_queryMessages_proto_rawDescGZIP(), []int{1}
}

func (x *QueryMessagesResponse) GetMessages() []*ContentMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *QueryMessagesResponse) GetNoMore() bool {
	if x != nil {
		return x.NoMore
	}
	return false
}

var File_queryMessages_proto protoreflect.FileDescriptor

var file_queryMessages_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x1a, 0x0a, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xce, 0x01, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x32, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x75, 0x69, 0x64,
	0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x66, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x75, 0x69, 0x64,
	0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0a, 0x73, 0x65, 0x6c, 0x66, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x65, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x4d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x6e, 0x6f, 0x4d, 0x6f, 0x72, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queryMessages_proto_rawDescOnce sync.Once
	file_queryMessages_proto_rawDescData = file_queryMessages_proto_rawDesc
)

func file_queryMessages_proto_rawDescGZIP() []byte {
	file_queryMessages_proto_rawDescOnce.Do(func() {
		file_queryMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_queryMessages_proto_rawDescData)
	})
	return file_queryMessages_proto_rawDescData
}

var file_queryMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_queryMessages_proto_goTypes = []interface{}{
	(*QueryMessagesRequest)(nil),  // 0: queryMessages.QueryMessagesRequest
	(*QueryMessagesResponse)(nil), // 1: queryMessages.QueryMessagesResponse
	(*UUID)(nil),                  // 2: uuid.UUID
	(*ContentMessage)(nil),        // 3: messages.ContentMessage
}
var file_queryMessages_proto_depIdxs = []int32{
	2, // 0: queryMessages.QueryMessagesRequest.conversationId:type_name -> uuid.UUID
	2, // 1: queryMessages.QueryMessagesRequest.selfUserId:type_name -> uuid.UUID
	3, // 2: queryMessages.QueryMessagesResponse.messages:type_name -> messages.ContentMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_queryMessages_proto_init() }
func file_queryMessages_proto_init() {
	if File_queryMessages_proto != nil {
		return
	}
	file_uuid_proto_init()
	file_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_queryMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queryMessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queryMessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queryMessages_proto_goTypes,
		DependencyIndexes: file_queryMessages_proto_depIdxs,
		MessageInfos:      file_queryMessages_proto_msgTypes,
	}.Build()
	File_queryMessages_proto = out.File
	file_queryMessages_proto_rawDesc = nil
	file_queryMessages_proto_goTypes = nil
	file_queryMessages_proto_depIdxs = nil
}
