// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: states.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationState int32

const (
	MigrationState_LEGACY            MigrationState = 0
	MigrationState_ARROYO_DEPRECATED MigrationState = 1
	MigrationState_ARROYO            MigrationState = 2
)

// Enum value maps for MigrationState.
var (
	MigrationState_name = map[int32]string{
		0: "LEGACY",
		1: "ARROYO_DEPRECATED",
		2: "ARROYO",
	}
	MigrationState_value = map[string]int32{
		"LEGACY":            0,
		"ARROYO_DEPRECATED": 1,
		"ARROYO":            2,
	}
)

func (x MigrationState) Enum() *MigrationState {
	p := new(MigrationState)
	*p = x
	return p
}

func (x MigrationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationState) Descriptor() protoreflect.EnumDescriptor {
	return file_states_proto_enumTypes[0].Descriptor()
}

func (MigrationState) Type() protoreflect.EnumType {
	return &file_states_proto_enumTypes[0]
}

func (x MigrationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationState.Descriptor instead.
func (MigrationState) EnumDescriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{0}
}

type SnapItemState int32

const (
	SnapItemState_UNKNOWN_SNAP_STATE SnapItemState = 0
	SnapItemState_VIEWED             SnapItemState = 1
	SnapItemState_UNVIEWED           SnapItemState = 2
	SnapItemState_SCREENSHOTTED      SnapItemState = 3
	SnapItemState_RECORDED           SnapItemState = 4
	SnapItemState_REPLAYED           SnapItemState = 5
)

// Enum value maps for SnapItemState.
var (
	SnapItemState_name = map[int32]string{
		0: "UNKNOWN_SNAP_STATE",
		1: "VIEWED",
		2: "UNVIEWED",
		3: "SCREENSHOTTED",
		4: "RECORDED",
		5: "REPLAYED",
	}
	SnapItemState_value = map[string]int32{
		"UNKNOWN_SNAP_STATE": 0,
		"VIEWED":             1,
		"UNVIEWED":           2,
		"SCREENSHOTTED":      3,
		"RECORDED":           4,
		"REPLAYED":           5,
	}
)

func (x SnapItemState) Enum() *SnapItemState {
	p := new(SnapItemState)
	*p = x
	return p
}

func (x SnapItemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapItemState) Descriptor() protoreflect.EnumDescriptor {
	return file_states_proto_enumTypes[1].Descriptor()
}

func (SnapItemState) Type() protoreflect.EnumType {
	return &file_states_proto_enumTypes[1]
}

func (x SnapItemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapItemState.Descriptor instead.
func (SnapItemState) EnumDescriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{1}
}

type ChatItemState int32

const (
	ChatItemState_UNKNOWN_CHAT_STATE                 ChatItemState = 0
	ChatItemState_CHAT_VIEWED                        ChatItemState = 1
	ChatItemState_CHAT_UNVIEWED                      ChatItemState = 2
	ChatItemState_CHAT_SCREENSHOTTED_VIEWED          ChatItemState = 3
	ChatItemState_CHAT_SCREENSHOTTED_UNVIEWED        ChatItemState = 4
	ChatItemState_CHAT_RECORDED_VIEWED               ChatItemState = 5
	ChatItemState_CHAT_RECORDED_UNVIEWED             ChatItemState = 6
	ChatItemState_CHAT_SAVED_VIEWED                  ChatItemState = 7
	ChatItemState_CHAT_SAVED_UNVIEWED                ChatItemState = 8
	ChatItemState_CHAT_ERASED                        ChatItemState = 9
	ChatItemState_CHAT_SAVED_TO_CAMERA_ROLL_VIEWED   ChatItemState = 10
	ChatItemState_CHAT_SAVED_TO_CAMERA_ROLL_UNVIEWED ChatItemState = 11
)

// Enum value maps for ChatItemState.
var (
	ChatItemState_name = map[int32]string{
		0:  "UNKNOWN_CHAT_STATE",
		1:  "CHAT_VIEWED",
		2:  "CHAT_UNVIEWED",
		3:  "CHAT_SCREENSHOTTED_VIEWED",
		4:  "CHAT_SCREENSHOTTED_UNVIEWED",
		5:  "CHAT_RECORDED_VIEWED",
		6:  "CHAT_RECORDED_UNVIEWED",
		7:  "CHAT_SAVED_VIEWED",
		8:  "CHAT_SAVED_UNVIEWED",
		9:  "CHAT_ERASED",
		10: "CHAT_SAVED_TO_CAMERA_ROLL_VIEWED",
		11: "CHAT_SAVED_TO_CAMERA_ROLL_UNVIEWED",
	}
	ChatItemState_value = map[string]int32{
		"UNKNOWN_CHAT_STATE":                 0,
		"CHAT_VIEWED":                        1,
		"CHAT_UNVIEWED":                      2,
		"CHAT_SCREENSHOTTED_VIEWED":          3,
		"CHAT_SCREENSHOTTED_UNVIEWED":        4,
		"CHAT_RECORDED_VIEWED":               5,
		"CHAT_RECORDED_UNVIEWED":             6,
		"CHAT_SAVED_VIEWED":                  7,
		"CHAT_SAVED_UNVIEWED":                8,
		"CHAT_ERASED":                        9,
		"CHAT_SAVED_TO_CAMERA_ROLL_VIEWED":   10,
		"CHAT_SAVED_TO_CAMERA_ROLL_UNVIEWED": 11,
	}
)

func (x ChatItemState) Enum() *ChatItemState {
	p := new(ChatItemState)
	*p = x
	return p
}

func (x ChatItemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatItemState) Descriptor() protoreflect.EnumDescriptor {
	return file_states_proto_enumTypes[2].Descriptor()
}

func (ChatItemState) Type() protoreflect.EnumType {
	return &file_states_proto_enumTypes[2]
}

func (x ChatItemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatItemState.Descriptor instead.
func (ChatItemState) EnumDescriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{2}
}

type ConversationItemState int32

const (
	ConversationItemState_UNKNOWN_CONVERSATION_STATE         ConversationItemState = 0
	ConversationItemState_CONVERSATION_CREATED_VIEWED        ConversationItemState = 1
	ConversationItemState_CONVERSATION_CREATED_UNVIEWED      ConversationItemState = 2
	ConversationItemState_CONVERSATION_MEMBER_ADDED_VIEWED   ConversationItemState = 3
	ConversationItemState_CONVERSATION_MEMBER_ADDED_UNVIEWED ConversationItemState = 4
	ConversationItemState_CONVERSATION_NAME_CHANGED_VIEWED   ConversationItemState = 5
	ConversationItemState_CONVERSATION_NAME_CHANGED_UNVIEWED ConversationItemState = 6
	ConversationItemState_CONVERSATION_MEMBER_KICKED         ConversationItemState = 7
)

// Enum value maps for ConversationItemState.
var (
	ConversationItemState_name = map[int32]string{
		0: "UNKNOWN_CONVERSATION_STATE",
		1: "CONVERSATION_CREATED_VIEWED",
		2: "CONVERSATION_CREATED_UNVIEWED",
		3: "CONVERSATION_MEMBER_ADDED_VIEWED",
		4: "CONVERSATION_MEMBER_ADDED_UNVIEWED",
		5: "CONVERSATION_NAME_CHANGED_VIEWED",
		6: "CONVERSATION_NAME_CHANGED_UNVIEWED",
		7: "CONVERSATION_MEMBER_KICKED",
	}
	ConversationItemState_value = map[string]int32{
		"UNKNOWN_CONVERSATION_STATE":         0,
		"CONVERSATION_CREATED_VIEWED":        1,
		"CONVERSATION_CREATED_UNVIEWED":      2,
		"CONVERSATION_MEMBER_ADDED_VIEWED":   3,
		"CONVERSATION_MEMBER_ADDED_UNVIEWED": 4,
		"CONVERSATION_NAME_CHANGED_VIEWED":   5,
		"CONVERSATION_NAME_CHANGED_UNVIEWED": 6,
		"CONVERSATION_MEMBER_KICKED":         7,
	}
)

func (x ConversationItemState) Enum() *ConversationItemState {
	p := new(ConversationItemState)
	*p = x
	return p
}

func (x ConversationItemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationItemState) Descriptor() protoreflect.EnumDescriptor {
	return file_states_proto_enumTypes[3].Descriptor()
}

func (ConversationItemState) Type() protoreflect.EnumType {
	return &file_states_proto_enumTypes[3]
}

func (x ConversationItemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationItemState.Descriptor instead.
func (ConversationItemState) EnumDescriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{3}
}

type CallItemState int32

const (
	CallItemState_UNKNOWN_CALL_STATE   CallItemState = 0
	CallItemState_CALL_MISSED_VIEWED   CallItemState = 1
	CallItemState_CALL_MISSED_UNVIEWED CallItemState = 2
	CallItemState_CALL_CALLED_VIEWED   CallItemState = 3
	CallItemState_CALL_CALLED_UNVIEWED CallItemState = 4
)

// Enum value maps for CallItemState.
var (
	CallItemState_name = map[int32]string{
		0: "UNKNOWN_CALL_STATE",
		1: "CALL_MISSED_VIEWED",
		2: "CALL_MISSED_UNVIEWED",
		3: "CALL_CALLED_VIEWED",
		4: "CALL_CALLED_UNVIEWED",
	}
	CallItemState_value = map[string]int32{
		"UNKNOWN_CALL_STATE":   0,
		"CALL_MISSED_VIEWED":   1,
		"CALL_MISSED_UNVIEWED": 2,
		"CALL_CALLED_VIEWED":   3,
		"CALL_CALLED_UNVIEWED": 4,
	}
)

func (x CallItemState) Enum() *CallItemState {
	p := new(CallItemState)
	*p = x
	return p
}

func (x CallItemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallItemState) Descriptor() protoreflect.EnumDescriptor {
	return file_states_proto_enumTypes[4].Descriptor()
}

func (CallItemState) Type() protoreflect.EnumType {
	return &file_states_proto_enumTypes[4]
}

func (x CallItemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallItemState.Descriptor instead.
func (CallItemState) EnumDescriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{4}
}

type MigrationInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MigrationSate MigrationState `protobuf:"varint,1,opt,name=migrationSate,proto3,enum=states.MigrationState" json:"migrationSate,omitempty"`
}

func (x *MigrationInfo) Reset() {
	*x = MigrationInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_states_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationInfo) ProtoMessage() {}

func (x *MigrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_states_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationInfo.ProtoReflect.Descriptor instead.
func (*MigrationInfo) Descriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationInfo) GetMigrationSate() MigrationState {
	if x != nil {
		return x.MigrationSate
	}
	return MigrationState_LEGACY
}

type SnapItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    SnapItemState `protobuf:"varint,1,opt,name=state,proto3,enum=states.SnapItemState" json:"state,omitempty"`
	HasAudio bool          `protobuf:"varint,2,opt,name=hasAudio,proto3" json:"hasAudio,omitempty"`
}

func (x *SnapItem) Reset() {
	*x = SnapItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_states_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapItem) ProtoMessage() {}

func (x *SnapItem) ProtoReflect() protoreflect.Message {
	mi := &file_states_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapItem.ProtoReflect.Descriptor instead.
func (*SnapItem) Descriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{1}
}

func (x *SnapItem) GetState() SnapItemState {
	if x != nil {
		return x.State
	}
	return SnapItemState_UNKNOWN_SNAP_STATE
}

func (x *SnapItem) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

type ChatItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State ChatItemState `protobuf:"varint,1,opt,name=state,proto3,enum=states.ChatItemState" json:"state,omitempty"`
}

func (x *ChatItem) Reset() {
	*x = ChatItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_states_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatItem) ProtoMessage() {}

func (x *ChatItem) ProtoReflect() protoreflect.Message {
	mi := &file_states_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatItem.ProtoReflect.Descriptor instead.
func (*ChatItem) Descriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{2}
}

func (x *ChatItem) GetState() ChatItemState {
	if x != nil {
		return x.State
	}
	return ChatItemState_UNKNOWN_CHAT_STATE
}

type CallItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State   CallItemState `protobuf:"varint,1,opt,name=state,proto3,enum=states.CallItemState" json:"state,omitempty"`
	IsVideo bool          `protobuf:"varint,2,opt,name=isVideo,proto3" json:"isVideo,omitempty"`
}

func (x *CallItem) Reset() {
	*x = CallItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_states_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallItem) ProtoMessage() {}

func (x *CallItem) ProtoReflect() protoreflect.Message {
	mi := &file_states_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallItem.ProtoReflect.Descriptor instead.
func (*CallItem) Descriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{3}
}

func (x *CallItem) GetState() CallItemState {
	if x != nil {
		return x.State
	}
	return CallItemState_UNKNOWN_CALL_STATE
}

func (x *CallItem) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

type ConversationItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State ConversationItemState `protobuf:"varint,1,opt,name=state,proto3,enum=states.ConversationItemState" json:"state,omitempty"`
}

func (x *ConversationItem) Reset() {
	*x = ConversationItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_states_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConversationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationItem) ProtoMessage() {}

func (x *ConversationItem) ProtoReflect() protoreflect.Message {
	mi := &file_states_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationItem.ProtoReflect.Descriptor instead.
func (*ConversationItem) Descriptor() ([]byte, []int) {
	return file_states_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationItem) GetState() ConversationItemState {
	if x != nil {
		return x.State
	}
	return ConversationItemState_UNKNOWN_CONVERSATION_STATE
}

var File_states_proto protoreflect.FileDescriptor

var file_states_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x0d, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3c, 0x0a, 0x0d, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x61, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x49, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x61, 0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x68, 0x61, 0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x37, 0x0a, 0x08, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x51, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x73, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x47, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a,
	0x3f, 0x0a, 0x0e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x45, 0x47, 0x41, 0x43, 0x59, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x41, 0x52, 0x52, 0x4f, 0x59, 0x4f, 0x5f, 0x44, 0x45, 0x50, 0x52, 0x45, 0x43, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x52, 0x52, 0x4f, 0x59, 0x4f, 0x10, 0x02,
	0x2a, 0x70, 0x0a, 0x0d, 0x53, 0x6e, 0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x4e, 0x41,
	0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x49, 0x45,
	0x57, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x53, 0x48, 0x4f,
	0x54, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44,
	0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x44,
	0x10, 0x05, 0x2a, 0xd0, 0x02, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x1d, 0x0a, 0x19, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x53,
	0x48, 0x4f, 0x54, 0x54, 0x45, 0x44, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x1f, 0x0a, 0x1b, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x53, 0x48,
	0x4f, 0x54, 0x54, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x04,
	0x12, 0x18, 0x0a, 0x14, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x45,
	0x44, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x48,
	0x41, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49,
	0x45, 0x57, 0x45, 0x44, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x53,
	0x41, 0x56, 0x45, 0x44, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x07, 0x12, 0x17, 0x0a,
	0x13, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49,
	0x45, 0x57, 0x45, 0x44, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x45,
	0x52, 0x41, 0x53, 0x45, 0x44, 0x10, 0x09, 0x12, 0x24, 0x0a, 0x20, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x5f,
	0x52, 0x4f, 0x4c, 0x4c, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x0a, 0x12, 0x26, 0x0a,
	0x22, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x43,
	0x41, 0x4d, 0x45, 0x52, 0x41, 0x5f, 0x52, 0x4f, 0x4c, 0x4c, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45,
	0x57, 0x45, 0x44, 0x10, 0x0b, 0x2a, 0xb7, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x1a, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x45,
	0x52, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12,
	0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x21, 0x0a, 0x1d, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x53, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x44, 0x45, 0x44,
	0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x03, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x4f, 0x4e,
	0x56, 0x45, 0x52, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52,
	0x5f, 0x41, 0x44, 0x44, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10,
	0x04, 0x12, 0x24, 0x0a, 0x20, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x53, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x44, 0x5f, 0x56,
	0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x05, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x4f, 0x4e, 0x56, 0x45,
	0x52, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x43, 0x48, 0x41,
	0x4e, 0x47, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x06, 0x12,
	0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4b, 0x49, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x07, 0x2a,
	0x8b, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x41, 0x4c,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x41, 0x4c,
	0x4c, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x45, 0x44, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x41, 0x4c, 0x4c, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x45, 0x44,
	0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x43,
	0x41, 0x4c, 0x4c, 0x5f, 0x43, 0x41, 0x4c, 0x4c, 0x45, 0x44, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x41, 0x4c, 0x4c, 0x5f, 0x43, 0x41, 0x4c, 0x4c,
	0x45, 0x44, 0x5f, 0x55, 0x4e, 0x56, 0x49, 0x45, 0x57, 0x45, 0x44, 0x10, 0x04, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_states_proto_rawDescOnce sync.Once
	file_states_proto_rawDescData = file_states_proto_rawDesc
)

func file_states_proto_rawDescGZIP() []byte {
	file_states_proto_rawDescOnce.Do(func() {
		file_states_proto_rawDescData = protoimpl.X.CompressGZIP(file_states_proto_rawDescData)
	})
	return file_states_proto_rawDescData
}

var file_states_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_states_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_states_proto_goTypes = []interface{}{
	(MigrationState)(0),        // 0: states.MigrationState
	(SnapItemState)(0),         // 1: states.SnapItemState
	(ChatItemState)(0),         // 2: states.ChatItemState
	(ConversationItemState)(0), // 3: states.ConversationItemState
	(CallItemState)(0),         // 4: states.CallItemState
	(*MigrationInfo)(nil),      // 5: states.MigrationInfo
	(*SnapItem)(nil),           // 6: states.SnapItem
	(*ChatItem)(nil),           // 7: states.ChatItem
	(*CallItem)(nil),           // 8: states.CallItem
	(*ConversationItem)(nil),   // 9: states.ConversationItem
}
var file_states_proto_depIdxs = []int32{
	0, // 0: states.MigrationInfo.migrationSate:type_name -> states.MigrationState
	1, // 1: states.SnapItem.state:type_name -> states.SnapItemState
	2, // 2: states.ChatItem.state:type_name -> states.ChatItemState
	4, // 3: states.CallItem.state:type_name -> states.CallItemState
	3, // 4: states.ConversationItem.state:type_name -> states.ConversationItemState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_states_proto_init() }
func file_states_proto_init() {
	if File_states_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_states_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_states_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_states_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_states_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_states_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConversationItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_states_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_states_proto_goTypes,
		DependencyIndexes: file_states_proto_depIdxs,
		EnumInfos:         file_states_proto_enumTypes,
		MessageInfos:      file_states_proto_msgTypes,
	}.Build()
	File_states_proto = out.File
	file_states_proto_rawDesc = nil
	file_states_proto_goTypes = nil
	file_states_proto_depIdxs = nil
}
