// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: transcription.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateAllowsTranscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowsTranscription bool `protobuf:"varint,1,opt,name=allowsTranscription,proto3" json:"allowsTranscription,omitempty"`
}

func (x *UpdateAllowsTranscription) Reset() {
	*x = UpdateAllowsTranscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcription_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAllowsTranscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllowsTranscription) ProtoMessage() {}

func (x *UpdateAllowsTranscription) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllowsTranscription.ProtoReflect.Descriptor instead.
func (*UpdateAllowsTranscription) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAllowsTranscription) GetAllowsTranscription() bool {
	if x != nil {
		return x.AllowsTranscription
	}
	return false
}

type UpdateAllowsTranscriptionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowsTranscription bool `protobuf:"varint,1,opt,name=allowsTranscription,proto3" json:"allowsTranscription,omitempty"`
}

func (x *UpdateAllowsTranscriptionResult) Reset() {
	*x = UpdateAllowsTranscriptionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcription_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAllowsTranscriptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllowsTranscriptionResult) ProtoMessage() {}

func (x *UpdateAllowsTranscriptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllowsTranscriptionResult.ProtoReflect.Descriptor instead.
func (*UpdateAllowsTranscriptionResult) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAllowsTranscriptionResult) GetAllowsTranscription() bool {
	if x != nil {
		return x.AllowsTranscription
	}
	return false
}

type AttachTranscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaReference          *MediaReference `protobuf:"bytes,1,opt,name=mediaReference,proto3" json:"mediaReference,omitempty"`
	MediaReferenceListIndex int32           `protobuf:"varint,2,opt,name=mediaReferenceListIndex,proto3" json:"mediaReferenceListIndex,omitempty"`
}

func (x *AttachTranscription) Reset() {
	*x = AttachTranscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcription_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachTranscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachTranscription) ProtoMessage() {}

func (x *AttachTranscription) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachTranscription.ProtoReflect.Descriptor instead.
func (*AttachTranscription) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{2}
}

func (x *AttachTranscription) GetMediaReference() *MediaReference {
	if x != nil {
		return x.MediaReference
	}
	return nil
}

func (x *AttachTranscription) GetMediaReferenceListIndex() int32 {
	if x != nil {
		return x.MediaReferenceListIndex
	}
	return 0
}

type AttachTranscriptionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaReferences *MediaReferences `protobuf:"bytes,1,opt,name=mediaReferences,proto3" json:"mediaReferences,omitempty"`
	Transcriptions  *Transcriptions  `protobuf:"bytes,2,opt,name=transcriptions,proto3" json:"transcriptions,omitempty"`
}

func (x *AttachTranscriptionResult) Reset() {
	*x = AttachTranscriptionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcription_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachTranscriptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachTranscriptionResult) ProtoMessage() {}

func (x *AttachTranscriptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachTranscriptionResult.ProtoReflect.Descriptor instead.
func (*AttachTranscriptionResult) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{3}
}

func (x *AttachTranscriptionResult) GetMediaReferences() *MediaReferences {
	if x != nil {
		return x.MediaReferences
	}
	return nil
}

func (x *AttachTranscriptionResult) GetTranscriptions() *Transcriptions {
	if x != nil {
		return x.Transcriptions
	}
	return nil
}

type Transcriptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transcriptions []*TranscriptionInfo `protobuf:"bytes,1,rep,name=transcriptions,proto3" json:"transcriptions,omitempty"`
}

func (x *Transcriptions) Reset() {
	*x = Transcriptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcription_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transcriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcriptions) ProtoMessage() {}

func (x *Transcriptions) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcriptions.ProtoReflect.Descriptor instead.
func (*Transcriptions) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{4}
}

func (x *Transcriptions) GetTranscriptions() []*TranscriptionInfo {
	if x != nil {
		return x.Transcriptions
	}
	return nil
}

type TranscriptionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaId                 *MediaId `protobuf:"bytes,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	MediaReferenceListIndex int32    `protobuf:"varint,2,opt,name=mediaReferenceListIndex,proto3" json:"mediaReferenceListIndex,omitempty"`
}

func (x *TranscriptionInfo) Reset() {
	*x = TranscriptionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcription_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionInfo) ProtoMessage() {}

func (x *TranscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionInfo.ProtoReflect.Descriptor instead.
func (*TranscriptionInfo) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{5}
}

func (x *TranscriptionInfo) GetMediaId() *MediaId {
	if x != nil {
		return x.MediaId
	}
	return nil
}

func (x *TranscriptionInfo) GetMediaReferenceListIndex() int32 {
	if x != nil {
		return x.MediaReferenceListIndex
	}
	return 0
}

var File_transcription_proto protoreflect.FileDescriptor

var file_transcription_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4d, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30,
	0x0a, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x53, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x73,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a,
	0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x17,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xa4, 0x01, 0x0a, 0x19, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x40, 0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5a, 0x0a,
	0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x48, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x77, 0x0a, 0x11, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28,
	0x0a, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x52,
	0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x17, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transcription_proto_rawDescOnce sync.Once
	file_transcription_proto_rawDescData = file_transcription_proto_rawDesc
)

func file_transcription_proto_rawDescGZIP() []byte {
	file_transcription_proto_rawDescOnce.Do(func() {
		file_transcription_proto_rawDescData = protoimpl.X.CompressGZIP(file_transcription_proto_rawDescData)
	})
	return file_transcription_proto_rawDescData
}

var file_transcription_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_transcription_proto_goTypes = []interface{}{
	(*UpdateAllowsTranscription)(nil),       // 0: transcription.UpdateAllowsTranscription
	(*UpdateAllowsTranscriptionResult)(nil), // 1: transcription.UpdateAllowsTranscriptionResult
	(*AttachTranscription)(nil),             // 2: transcription.AttachTranscription
	(*AttachTranscriptionResult)(nil),       // 3: transcription.AttachTranscriptionResult
	(*Transcriptions)(nil),                  // 4: transcription.Transcriptions
	(*TranscriptionInfo)(nil),               // 5: transcription.TranscriptionInfo
	(*MediaReference)(nil),                  // 6: media.MediaReference
	(*MediaReferences)(nil),                 // 7: media.MediaReferences
	(*MediaId)(nil),                         // 8: media.MediaId
}
var file_transcription_proto_depIdxs = []int32{
	6, // 0: transcription.AttachTranscription.mediaReference:type_name -> media.MediaReference
	7, // 1: transcription.AttachTranscriptionResult.mediaReferences:type_name -> media.MediaReferences
	4, // 2: transcription.AttachTranscriptionResult.transcriptions:type_name -> transcription.Transcriptions
	5, // 3: transcription.Transcriptions.transcriptions:type_name -> transcription.TranscriptionInfo
	8, // 4: transcription.TranscriptionInfo.mediaId:type_name -> media.MediaId
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_transcription_proto_init() }
func file_transcription_proto_init() {
	if File_transcription_proto != nil {
		return
	}
	file_media_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_transcription_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAllowsTranscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcription_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAllowsTranscriptionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcription_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachTranscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcription_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachTranscriptionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcription_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transcriptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcription_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscriptionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transcription_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transcription_proto_goTypes,
		DependencyIndexes: file_transcription_proto_depIdxs,
		MessageInfos:      file_transcription_proto_msgTypes,
	}.Build()
	File_transcription_proto = out.File
	file_transcription_proto_rawDesc = nil
	file_transcription_proto_goTypes = nil
	file_transcription_proto_depIdxs = nil
}
