// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: updateResult.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadTimestamp int64 `protobuf:"varint,1,opt,name=readTimestamp,proto3" json:"readTimestamp,omitempty"`
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{0}
}

func (x *ReadResult) GetReadTimestamp() int64 {
	if x != nil {
		return x.ReadTimestamp
	}
	return 0
}

type ReleaseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReleaseResult) Reset() {
	*x = ReleaseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResult) ProtoMessage() {}

func (x *ReleaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResult.ProtoReflect.Descriptor instead.
func (*ReleaseResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{1}
}

type SaveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvelopeEncryption *EnvelopeEncryption         `protobuf:"bytes,1,opt,name=envelopeEncryption,proto3" json:"envelopeEncryption,omitempty"`
	MediaReferences    *MediaReferences            `protobuf:"bytes,2,opt,name=mediaReferences,proto3" json:"mediaReferences,omitempty"`
	Thumbnails         *ContentEnvelope_Thumbnails `protobuf:"bytes,3,opt,name=thumbnails,proto3" json:"thumbnails,omitempty"`
}

func (x *SaveResult) Reset() {
	*x = SaveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResult) ProtoMessage() {}

func (x *SaveResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResult.ProtoReflect.Descriptor instead.
func (*SaveResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{2}
}

func (x *SaveResult) GetEnvelopeEncryption() *EnvelopeEncryption {
	if x != nil {
		return x.EnvelopeEncryption
	}
	return nil
}

func (x *SaveResult) GetMediaReferences() *MediaReferences {
	if x != nil {
		return x.MediaReferences
	}
	return nil
}

func (x *SaveResult) GetThumbnails() *ContentEnvelope_Thumbnails {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

type UnsaveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnsaveResult) Reset() {
	*x = UnsaveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsaveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsaveResult) ProtoMessage() {}

func (x *UnsaveResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsaveResult.ProtoReflect.Descriptor instead.
func (*UnsaveResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{3}
}

type EraseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedMessage *ContentMessage `protobuf:"bytes,1,opt,name=updatedMessage,proto3" json:"updatedMessage,omitempty"`
}

func (x *EraseResult) Reset() {
	*x = EraseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EraseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseResult) ProtoMessage() {}

func (x *EraseResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseResult.ProtoReflect.Descriptor instead.
func (*EraseResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{4}
}

func (x *EraseResult) GetUpdatedMessage() *ContentMessage {
	if x != nil {
		return x.UpdatedMessage
	}
	return nil
}

type EraseStoryMediaResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaReferences *MediaReferences            `protobuf:"bytes,1,opt,name=mediaReferences,proto3" json:"mediaReferences,omitempty"`
	Thumbnails      *ContentEnvelope_Thumbnails `protobuf:"bytes,2,opt,name=thumbnails,proto3" json:"thumbnails,omitempty"`
}

func (x *EraseStoryMediaResult) Reset() {
	*x = EraseStoryMediaResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EraseStoryMediaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseStoryMediaResult) ProtoMessage() {}

func (x *EraseStoryMediaResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseStoryMediaResult.ProtoReflect.Descriptor instead.
func (*EraseStoryMediaResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{5}
}

func (x *EraseStoryMediaResult) GetMediaReferences() *MediaReferences {
	if x != nil {
		return x.MediaReferences
	}
	return nil
}

func (x *EraseStoryMediaResult) GetThumbnails() *ContentEnvelope_Thumbnails {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

type TombstoneResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TombstoneResult) Reset() {
	*x = TombstoneResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TombstoneResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TombstoneResult) ProtoMessage() {}

func (x *TombstoneResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TombstoneResult.ProtoReflect.Descriptor instead.
func (*TombstoneResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{6}
}

type SaveToCameraRollResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveToCameraRollResult) Reset() {
	*x = SaveToCameraRollResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveToCameraRollResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveToCameraRollResult) ProtoMessage() {}

func (x *SaveToCameraRollResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveToCameraRollResult.ProtoReflect.Descriptor instead.
func (*SaveToCameraRollResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{7}
}

type ScreenshotResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScreenshotResult) Reset() {
	*x = ScreenshotResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenshotResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResult) ProtoMessage() {}

func (x *ScreenshotResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResult.ProtoReflect.Descriptor instead.
func (*ScreenshotResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{8}
}

type ScreenRecordResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScreenRecordResult) Reset() {
	*x = ScreenRecordResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenRecordResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenRecordResult) ProtoMessage() {}

func (x *ScreenRecordResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenRecordResult.ProtoReflect.Descriptor instead.
func (*ScreenRecordResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{9}
}

type ReplayResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplayCount int32 `protobuf:"varint,1,opt,name=replayCount,proto3" json:"replayCount,omitempty"`
}

func (x *ReplayResult) Reset() {
	*x = ReplayResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplayResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResult) ProtoMessage() {}

func (x *ReplayResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResult.ProtoReflect.Descriptor instead.
func (*ReplayResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayResult) GetReplayCount() int32 {
	if x != nil {
		return x.ReplayCount
	}
	return 0
}

type AddEelReEncryptionInitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EelReEncryptionInits []*EelReEncryptionInit `protobuf:"bytes,1,rep,name=eelReEncryptionInits,proto3" json:"eelReEncryptionInits,omitempty"`
}

func (x *AddEelReEncryptionInitResult) Reset() {
	*x = AddEelReEncryptionInitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEelReEncryptionInitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEelReEncryptionInitResult) ProtoMessage() {}

func (x *AddEelReEncryptionInitResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEelReEncryptionInitResult.ProtoReflect.Descriptor instead.
func (*AddEelReEncryptionInitResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{11}
}

func (x *AddEelReEncryptionInitResult) GetEelReEncryptionInits() []*EelReEncryptionInit {
	if x != nil {
		return x.EelReEncryptionInits
	}
	return nil
}

type AppendEelReEncryptionDestinationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EelReEncryptionInits     []*EelReEncryptionInit    `protobuf:"bytes,1,rep,name=eelReEncryptionInits,proto3" json:"eelReEncryptionInits,omitempty"`
	EelDestinationEncryption *EelDestinationEncryption `protobuf:"bytes,2,opt,name=eelDestinationEncryption,proto3" json:"eelDestinationEncryption,omitempty"`
}

func (x *AppendEelReEncryptionDestinationResult) Reset() {
	*x = AppendEelReEncryptionDestinationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateResult_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendEelReEncryptionDestinationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEelReEncryptionDestinationResult) ProtoMessage() {}

func (x *AppendEelReEncryptionDestinationResult) ProtoReflect() protoreflect.Message {
	mi := &file_updateResult_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEelReEncryptionDestinationResult.ProtoReflect.Descriptor instead.
func (*AppendEelReEncryptionDestinationResult) Descriptor() ([]byte, []int) {
	return file_updateResult_proto_rawDescGZIP(), []int{12}
}

func (x *AppendEelReEncryptionDestinationResult) GetEelReEncryptionInits() []*EelReEncryptionInit {
	if x != nil {
		return x.EelReEncryptionInits
	}
	return nil
}

func (x *AppendEelReEncryptionDestinationResult) GetEelDestinationEncryption() *EelDestinationEncryption {
	if x != nil {
		return x.EelDestinationEncryption
	}
	return nil
}

var File_updateResult_proto protoreflect.FileDescriptor

var file_updateResult_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x1a, 0x0c, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x0a, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4a, 0x0a, 0x12, 0x65, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x12, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x5f, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x55, 0x6e, 0x73, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x4f, 0x0a, 0x0b, 0x45, 0x72, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x15, 0x45, 0x72, 0x61, 0x73, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x79, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x40,
	0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52,
	0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x4b, 0x0a, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x5f, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x11, 0x0a,
	0x0f, 0x54, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x18, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x54, 0x6f, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x52, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x14,
	0x0a, 0x12, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x45, 0x65, 0x6c,
	0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4f, 0x0a, 0x14, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x45, 0x65,
	0x6c, 0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x14, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x73, 0x22, 0xd7, 0x01, 0x0a, 0x26, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x45, 0x65, 0x6c, 0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x4f, 0x0a, 0x14, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x45, 0x65, 0x6c, 0x52, 0x65, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x14, 0x65,
	0x65, 0x6c, 0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x69, 0x74, 0x73, 0x12, 0x5c, 0x0a, 0x18, 0x65, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x45,
	0x65, 0x6c, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x18, 0x65, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_updateResult_proto_rawDescOnce sync.Once
	file_updateResult_proto_rawDescData = file_updateResult_proto_rawDesc
)

func file_updateResult_proto_rawDescGZIP() []byte {
	file_updateResult_proto_rawDescOnce.Do(func() {
		file_updateResult_proto_rawDescData = protoimpl.X.CompressGZIP(file_updateResult_proto_rawDescData)
	})
	return file_updateResult_proto_rawDescData
}

var file_updateResult_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_updateResult_proto_goTypes = []interface{}{
	(*ReadResult)(nil),                             // 0: updateResult.ReadResult
	(*ReleaseResult)(nil),                          // 1: updateResult.ReleaseResult
	(*SaveResult)(nil),                             // 2: updateResult.SaveResult
	(*UnsaveResult)(nil),                           // 3: updateResult.UnsaveResult
	(*EraseResult)(nil),                            // 4: updateResult.EraseResult
	(*EraseStoryMediaResult)(nil),                  // 5: updateResult.EraseStoryMediaResult
	(*TombstoneResult)(nil),                        // 6: updateResult.TombstoneResult
	(*SaveToCameraRollResult)(nil),                 // 7: updateResult.SaveToCameraRollResult
	(*ScreenshotResult)(nil),                       // 8: updateResult.ScreenshotResult
	(*ScreenRecordResult)(nil),                     // 9: updateResult.ScreenRecordResult
	(*ReplayResult)(nil),                           // 10: updateResult.ReplayResult
	(*AddEelReEncryptionInitResult)(nil),           // 11: updateResult.AddEelReEncryptionInitResult
	(*AppendEelReEncryptionDestinationResult)(nil), // 12: updateResult.AppendEelReEncryptionDestinationResult
	(*EnvelopeEncryption)(nil),                     // 13: crypto.EnvelopeEncryption
	(*MediaReferences)(nil),                        // 14: media.MediaReferences
	(*ContentEnvelope_Thumbnails)(nil),             // 15: contentEnvelope.ContentEnvelope_Thumbnails
	(*ContentMessage)(nil),                         // 16: messages.ContentMessage
	(*EelReEncryptionInit)(nil),                    // 17: crypto.EelReEncryptionInit
	(*EelDestinationEncryption)(nil),               // 18: crypto.EelDestinationEncryption
}
var file_updateResult_proto_depIdxs = []int32{
	13, // 0: updateResult.SaveResult.envelopeEncryption:type_name -> crypto.EnvelopeEncryption
	14, // 1: updateResult.SaveResult.mediaReferences:type_name -> media.MediaReferences
	15, // 2: updateResult.SaveResult.thumbnails:type_name -> contentEnvelope.ContentEnvelope_Thumbnails
	16, // 3: updateResult.EraseResult.updatedMessage:type_name -> messages.ContentMessage
	14, // 4: updateResult.EraseStoryMediaResult.mediaReferences:type_name -> media.MediaReferences
	15, // 5: updateResult.EraseStoryMediaResult.thumbnails:type_name -> contentEnvelope.ContentEnvelope_Thumbnails
	17, // 6: updateResult.AddEelReEncryptionInitResult.eelReEncryptionInits:type_name -> crypto.EelReEncryptionInit
	17, // 7: updateResult.AppendEelReEncryptionDestinationResult.eelReEncryptionInits:type_name -> crypto.EelReEncryptionInit
	18, // 8: updateResult.AppendEelReEncryptionDestinationResult.eelDestinationEncryption:type_name -> crypto.EelDestinationEncryption
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_updateResult_proto_init() }
func file_updateResult_proto_init() {
	if File_updateResult_proto != nil {
		return
	}
	file_crypto_proto_init()
	file_messages_proto_init()
	file_contentEnvelope_proto_init()
	file_media_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_updateResult_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsaveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EraseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EraseStoryMediaResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TombstoneResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveToCameraRollResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreenshotResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreenRecordResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplayResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEelReEncryptionInitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updateResult_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendEelReEncryptionDestinationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_updateResult_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updateResult_proto_goTypes,
		DependencyIndexes: file_updateResult_proto_depIdxs,
		MessageInfos:      file_updateResult_proto_msgTypes,
	}.Build()
	File_updateResult_proto = out.File
	file_updateResult_proto_rawDesc = nil
	file_updateResult_proto_goTypes = nil
	file_updateResult_proto_depIdxs = nil
}
